export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as ServicesSection } from './ServicesSection'
export { default as WorkSection } from './WorkSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as BlogSection } from './BlogSection'
export { default as ContactSection } from './ContactSection'
