// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:about-image-reveal
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oWX1kejFurBeF06W1EY5/PBTLjRnBqN2CpHkqlRz5/Dp_z08Zc2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var cycleOrder = ["rDvyAktkg", "QxE2euxU3", "NNBAldQ6M"];
var serializationHash = "framer-Gy7yo";
var variantClassNames = {
	NNBAldQ6M: "framer-v-1j3pup",
	QxE2euxU3: "framer-v-zosr1s",
	rDvyAktkg: "framer-v-bkf1e1",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var radiusForCorner = (value, cornerIndex) => {
	if (typeof value === "number" && Number.isFinite(value))
		return Math.max(0, value) + "px";
	if (typeof value !== "string" || typeof cornerIndex !== "number")
		return void 0;
	const segments = value.split(" ");
	return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};
var transition1 = {
	duration: 0,
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	bounce: 0,
	delay: 0.5,
	duration: 1,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Step 1": "QxE2euxU3",
	"Step 2": "NNBAldQ6M",
	Default: "rDvyAktkg",
};
var getProps = ({ height, id, image, radius, width, ...props }) => {
	return {
		...props,
		AmdgBgogp: radius ?? props.AmdgBgogp ?? "8px",
		iR9TM5Vwb: image ??
			props.iR9TM5Vwb ?? {
				alt: "Blue-toned illustration of a bearded man with glasses against a black background",
				pixelHeight: 1456,
				pixelWidth: 1056,
				src: "https://framerusercontent.com/images/OcbaJPyRVq8hSu3u1ZCWoVaYzKM.png?scale-down-to=512&width=1056&height=1456",
				srcSet:
					"https://framerusercontent.com/images/OcbaJPyRVq8hSu3u1ZCWoVaYzKM.png?scale-down-to=1024&width=1056&height=1456 742w,https://framerusercontent.com/images/OcbaJPyRVq8hSu3u1ZCWoVaYzKM.png?width=1056&height=1456 1056w",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "rDvyAktkg",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		AmdgBgogp,
		iR9TM5Vwb,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "rDvyAktkg",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearp4ync5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("NNBAldQ6M", true), 500);
	});
	useOnVariantChange(baseVariant, {
		QxE2euxU3: onAppearp4ync5,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							NNBAldQ6M: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-bkf1e1",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"rDvyAktkg"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							borderBottomLeftRadius: radiusForCorner(AmdgBgogp, 3),
							borderBottomRightRadius: radiusForCorner(AmdgBgogp, 2),
							borderTopLeftRadius: radiusForCorner(AmdgBgogp, 0),
							borderTopRightRadius: radiusForCorner(AmdgBgogp, 1),
							...style,
						}}
						{...addPropertyOverrides(
							{
								NNBAldQ6M: {
									"data-framer-name": "Step 2",
								},
								QxE2euxU3: {
									"data-framer-name": "Step 1",
									"data-highlight": true,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-139nmev"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"KTHdpOz3U"}
							style={{
								backgroundColor:
									"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
								borderBottomLeftRadius: radiusForCorner(AmdgBgogp, 3),
								borderBottomRightRadius: radiusForCorner(AmdgBgogp, 2),
								borderTopLeftRadius: radiusForCorner(AmdgBgogp, 0),
								borderTopRightRadius: radiusForCorner(AmdgBgogp, 1),
							}}
						>
							<Image
								as={"figure"}
								background={{
									alt: "BG Grain",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 364) - 0 - 364) / 2 +
												0 +
												0) +
											0,
									),
									pixelHeight: 1456,
									pixelWidth: 1056,
									sizes: componentViewport?.width || "100vw",
									src: "https://framerusercontent.com/images/W9ukVzmx4t2YwHWqs9AzDopxaM.png?width=1056&height=1456",
									srcSet:
										"https://framerusercontent.com/images/W9ukVzmx4t2YwHWqs9AzDopxaM.png?scale-down-to=1024&width=1056&height=1456 742w,https://framerusercontent.com/images/W9ukVzmx4t2YwHWqs9AzDopxaM.png?width=1056&height=1456 1056w",
								}}
								className={"framer-w78uey"}
								data-framer-name={"BG Grain"}
								layoutDependency={layoutDependency}
								layoutId={"uNgZjOVi2"}
								style={{
									borderBottomLeftRadius: radiusForCorner(AmdgBgogp, 3),
									borderBottomRightRadius: radiusForCorner(AmdgBgogp, 2),
									borderTopLeftRadius: radiusForCorner(AmdgBgogp, 0),
									borderTopRightRadius: radiusForCorner(AmdgBgogp, 1),
								}}
							/>
							<ImageWithFX
								as={"figure"}
								background={{
									alt: "Blue-toned illustration of a bearded man with glasses against a black background",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 364) - 0 - 364) / 2 +
												0 +
												0) +
											0 +
											0,
									),
									pixelHeight: 1456,
									pixelWidth: 1056,
									sizes: componentViewport?.width || "100vw",
									...toResponsiveImage(iR9TM5Vwb),
								}}
								className={"framer-13rhlh7"}
								layoutDependency={layoutDependency}
								layoutId={"ZQhg6mMgd"}
								style={{
									borderBottomLeftRadius: radiusForCorner(AmdgBgogp, 3),
									borderBottomRightRadius: radiusForCorner(AmdgBgogp, 2),
									borderTopLeftRadius: radiusForCorner(AmdgBgogp, 0),
									borderTopRightRadius: radiusForCorner(AmdgBgogp, 1),
								}}
								{...addPropertyOverrides(
									{
										NNBAldQ6M: {
											__framer__animate: {
												transition: transition3,
											},
											__framer__animateOnce: false,
											__framer__enter: animation,
											__framer__styleAppearEffectEnabled: true,
											__framer__threshold: 0.5,
											__perspectiveFX: false,
											__smartComponentFX: true,
											__targetOpacity: 1,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion.div
								className={"framer-1fdy8yq"}
								data-framer-name={"White Overlay"}
								layoutDependency={layoutDependency}
								layoutId={"J1szWjBTl"}
								style={{
									backgroundColor:
										"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
									borderBottomLeftRadius: radiusForCorner(AmdgBgogp, 3),
									borderBottomRightRadius: radiusForCorner(AmdgBgogp, 2),
									borderTopLeftRadius: radiusForCorner(AmdgBgogp, 0),
									borderTopRightRadius: radiusForCorner(AmdgBgogp, 1),
									opacity: 1,
								}}
								variants={{
									NNBAldQ6M: {
										opacity: 0,
									},
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Gy7yo.framer-1yxxc0a, .framer-Gy7yo .framer-1yxxc0a { display: block; }",
	".framer-Gy7yo.framer-bkf1e1 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 264px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Gy7yo .framer-139nmev { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Gy7yo .framer-w78uey { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; z-index: 0; }",
	".framer-Gy7yo .framer-13rhlh7 { aspect-ratio: 0.7252747252747253 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 364px); overflow: visible; position: relative; width: 100%; }",
	".framer-Gy7yo .framer-1fdy8yq { bottom: 0px; flex: none; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
];
var FramerDp_z08Zc2 = withCSS(Component, css, "framer-Gy7yo");
var stdin_default = FramerDp_z08Zc2;
FramerDp_z08Zc2.displayName = "About Image Reveal";
FramerDp_z08Zc2.defaultProps = {
	height: 364,
	width: 264,
};
addPropertyControls(FramerDp_z08Zc2, {
	variant: {
		options: ["rDvyAktkg", "QxE2euxU3", "NNBAldQ6M"],
		optionTitles: ["Default", "Step 1", "Step 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	AmdgBgogp: {
		defaultValue: "8px",
		title: "Radius",
		type: ControlType.BorderRadius,
	},
	iR9TM5Vwb: {
		__defaultAssetReference:
			"data:framer/asset-reference,OcbaJPyRVq8hSu3u1ZCWoVaYzKM.png?originalFilename=image+-+about+me.png&width=1056&height=1456",
		__vekterDefault: {
			alt: "Blue-toned illustration of a bearded man with glasses against a black background",
			assetReference:
				"data:framer/asset-reference,OcbaJPyRVq8hSu3u1ZCWoVaYzKM.png?originalFilename=image+-+about+me.png&width=1056&height=1456",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerDp_z08Zc2,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:about-image-reveal
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "rDvyAktkg",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AboutImageRevealFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var about_image_reveal_default = ComponentWithRoot;
export { about_image_reveal_default as default };
