// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default - (Desktop + Tablet)' | '1 - (Desktop + Tablet)' | '2 - (Desktop + Tablet)' | '3 - (Desktop + Tablet)' | '4 - (Desktop + Tablet)' | '5 - (Desktop + Tablet)' | 'Default - (Phone)' | '1 - (Phone)' | '2 - (Phone)' | '3 - (Phone)' | '4 - (Phone)' | '5 - (Phone)' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-KMX4X5OV.js";
import { AvoidLayoutJumping } from "./chunks/chunk-C2KZ2SUB.js";
import "./chunks/chunk-UOQGEBQU.js";
import "./chunks/chunk-3XNB3BOA.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:achievement-cards-animated
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6wlDaLDBeHA2iLCHg3T8/zFMp0LVXA5x7mjSFEiQd/wKxMV30eJ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var AchievementCardFonts = getFonts(stdin_default);
var cycleOrder = [
	"iKjmMWeqB",
	"S7qwU261K",
	"byIjNHLdI",
	"grc3Z8AOG",
	"zRG9ZrAis",
	"Fs5MnUuYF",
	"c4QFbVLAH",
	"PHdrEJxpc",
	"YH5Zh04Gf",
	"lyejRH0mG",
	"uLKAs1ePU",
	"IBPTjmJqu",
];
var serializationHash = "framer-1ULUj";
var variantClassNames = {
	byIjNHLdI: "framer-v-nga46w",
	c4QFbVLAH: "framer-v-35ac92",
	Fs5MnUuYF: "framer-v-iotgh2",
	grc3Z8AOG: "framer-v-ayx20f",
	IBPTjmJqu: "framer-v-1lebkyx",
	iKjmMWeqB: "framer-v-77ms3x",
	lyejRH0mG: "framer-v-vaffwg",
	PHdrEJxpc: "framer-v-yr7qxp",
	S7qwU261K: "framer-v-15z3wwe",
	uLKAs1ePU: "framer-v-1386qk9",
	YH5Zh04Gf: "framer-v-1d0cg17",
	zRG9ZrAis: "framer-v-3810q0",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var transition2 = {
	bounce: 0,
	delay: 0,
	duration: 1,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"1 - (Desktop + Tablet)": "S7qwU261K",
	"1 - (Phone)": "PHdrEJxpc",
	"2 - (Desktop + Tablet)": "byIjNHLdI",
	"2 - (Phone)": "YH5Zh04Gf",
	"3 - (Desktop + Tablet)": "grc3Z8AOG",
	"3 - (Phone)": "lyejRH0mG",
	"4 - (Desktop + Tablet)": "zRG9ZrAis",
	"4 - (Phone)": "uLKAs1ePU",
	"5 - (Desktop + Tablet)": "Fs5MnUuYF",
	"5 - (Phone)": "IBPTjmJqu",
	"Default - (Desktop + Tablet)": "iKjmMWeqB",
	"Default - (Phone)": "c4QFbVLAH",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "iKjmMWeqB",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "iKjmMWeqB",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1r6rsdy = activeVariantCallback(async (...args) => {
		setVariant("S7qwU261K", true);
	});
	const onAppear1n1wrms = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("byIjNHLdI", true), 200);
	});
	const onAppear1mul7q5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("grc3Z8AOG", true), 200);
	});
	const onAppear182o3bb = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("zRG9ZrAis", true), 200);
	});
	const onAppear1bqtxo7 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("Fs5MnUuYF", true), 200);
	});
	const onAppear959gtt = activeVariantCallback(async (...args) => {
		setVariant("PHdrEJxpc", true);
	});
	const onAppearghcmdq = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("YH5Zh04Gf", true), 200);
	});
	const onAppeareg5ira = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("lyejRH0mG", true), 200);
	});
	const onAppear144qie1 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("uLKAs1ePU", true), 200);
	});
	const onAppear1xydvx6 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("IBPTjmJqu", true), 200);
	});
	useOnVariantChange(baseVariant, {
		byIjNHLdI: onAppear1mul7q5,
		c4QFbVLAH: onAppear959gtt,
		default: onAppear1r6rsdy,
		Fs5MnUuYF: void 0,
		grc3Z8AOG: onAppear182o3bb,
		IBPTjmJqu: void 0,
		lyejRH0mG: onAppear144qie1,
		PHdrEJxpc: onAppearghcmdq,
		S7qwU261K: onAppear1n1wrms,
		uLKAs1ePU: onAppear1xydvx6,
		YH5Zh04Gf: onAppeareg5ira,
		zRG9ZrAis: onAppear1bqtxo7,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							byIjNHLdI: {
								value: transition2,
							},
							Fs5MnUuYF: {
								value: transition2,
							},
							grc3Z8AOG: {
								value: transition2,
							},
							IBPTjmJqu: {
								value: transition2,
							},
							lyejRH0mG: {
								value: transition2,
							},
							PHdrEJxpc: {
								value: transition2,
							},
							S7qwU261K: {
								value: transition2,
							},
							uLKAs1ePU: {
								value: transition2,
							},
							YH5Zh04Gf: {
								value: transition2,
							},
							zRG9ZrAis: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-77ms3x",
							className,
							classNames,
						)}
						data-framer-name={"Default - (Desktop + Tablet)"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"iKjmMWeqB"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								byIjNHLdI: {
									"data-framer-name": "2 - (Desktop + Tablet)",
								},
								c4QFbVLAH: {
									"data-framer-name": "Default - (Phone)",
								},
								Fs5MnUuYF: {
									"data-framer-name": "5 - (Desktop + Tablet)",
									"data-highlight": void 0,
								},
								grc3Z8AOG: {
									"data-framer-name": "3 - (Desktop + Tablet)",
								},
								IBPTjmJqu: {
									"data-framer-name": "5 - (Phone)",
									"data-highlight": void 0,
								},
								lyejRH0mG: {
									"data-framer-name": "3 - (Phone)",
								},
								PHdrEJxpc: {
									"data-framer-name": "1 - (Phone)",
								},
								S7qwU261K: {
									"data-framer-name": "1 - (Desktop + Tablet)",
								},
								uLKAs1ePU: {
									"data-framer-name": "4 - (Phone)",
								},
								YH5Zh04Gf: {
									"data-framer-name": "2 - (Phone)",
								},
								zRG9ZrAis: {
									"data-framer-name": "4 - (Desktop + Tablet)",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1uiekmj-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"pxO0xLsDU-container"}
								nodeId={"pxO0xLsDU"}
								rendersWithMotion={true}
								scopeId={"wKxMV30eJ"}
							>
								<AvoidLayoutJumping
									direction={"vertical"}
									height={"100%"}
									id={"pxO0xLsDU"}
									layoutId={"pxO0xLsDU"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={76}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-817nyp-container"}
								data-framer-name={"Achievement 1"}
								layoutDependency={layoutDependency}
								layoutId={"EIqqiSzS3-container"}
								name={"Achievement 1"}
								nodeId={"EIqqiSzS3"}
								rendersWithMotion={true}
								scopeId={"wKxMV30eJ"}
							>
								{_jsx(stdin_default, {
									BdUMN0rHF:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									ga_gk_gOP: "16px",
									height: "100%",
									id: "EIqqiSzS3",
									layoutId: "EIqqiSzS3",
									lpvxdnNhC: 0.2,
									name: "Achievement 1",
									style: {
										width: "100%",
									},
									UHOhwilMb: "120+",
									variant: "eohM_12uA",
									W0ThdLvu3:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									width: "100%",
									YsjACKB4l: "Projects Completed",
									...addPropertyOverrides(
										{
											c4QFbVLAH: {
												variant: "m2AGcC4bQ",
											},
											IBPTjmJqu: {
												variant: "m2AGcC4bQ",
											},
											lyejRH0mG: {
												variant: "m2AGcC4bQ",
											},
											PHdrEJxpc: {
												variant: "m2AGcC4bQ",
											},
											uLKAs1ePU: {
												variant: "m2AGcC4bQ",
											},
											YH5Zh04Gf: {
												variant: "m2AGcC4bQ",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={76}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
							{...addPropertyOverrides(
								{
									byIjNHLdI: {
										y: (componentViewport?.y || 0) + 0 + 76,
									},
									Fs5MnUuYF: {
										y: (componentViewport?.y || 0) + 0 + 76,
									},
									grc3Z8AOG: {
										y: (componentViewport?.y || 0) + 0 + 76,
									},
									IBPTjmJqu: {
										y: (componentViewport?.y || 0) + 0 + 76,
									},
									lyejRH0mG: {
										y: (componentViewport?.y || 0) + 0 + 76,
									},
									uLKAs1ePU: {
										y: (componentViewport?.y || 0) + 0 + 76,
									},
									YH5Zh04Gf: {
										y: (componentViewport?.y || 0) + 0 + 76,
									},
									zRG9ZrAis: {
										y: (componentViewport?.y || 0) + 0 + 76,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1tsbq36-container"}
								data-framer-name={"Achievement 2"}
								layoutDependency={layoutDependency}
								layoutId={"QVtIZSVEC-container"}
								name={"Achievement 2"}
								nodeId={"QVtIZSVEC"}
								rendersWithMotion={true}
								scopeId={"wKxMV30eJ"}
								style={{
									opacity: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									byIjNHLdI: {
										opacity: 1,
									},
									Fs5MnUuYF: {
										opacity: 1,
									},
									grc3Z8AOG: {
										opacity: 1,
									},
									IBPTjmJqu: {
										opacity: 1,
									},
									lyejRH0mG: {
										opacity: 1,
									},
									uLKAs1ePU: {
										opacity: 1,
									},
									YH5Zh04Gf: {
										opacity: 1,
									},
									zRG9ZrAis: {
										opacity: 1,
									},
								}}
								{...addPropertyOverrides(
									{
										byIjNHLdI: {
											transformTemplate: void 0,
										},
										Fs5MnUuYF: {
											transformTemplate: void 0,
										},
										grc3Z8AOG: {
											transformTemplate: void 0,
										},
										IBPTjmJqu: {
											transformTemplate: void 0,
										},
										lyejRH0mG: {
											transformTemplate: void 0,
										},
										uLKAs1ePU: {
											transformTemplate: void 0,
										},
										YH5Zh04Gf: {
											transformTemplate: void 0,
										},
										zRG9ZrAis: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									BdUMN0rHF:
										"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
									ga_gk_gOP: "16px",
									height: "100%",
									id: "QVtIZSVEC",
									layoutId: "QVtIZSVEC",
									lpvxdnNhC: 0.4,
									name: "Achievement 2",
									style: {
										width: "100%",
									},
									UHOhwilMb: "10+",
									variant: "eohM_12uA",
									W0ThdLvu3:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									width: "100%",
									YsjACKB4l: "Years of Experience",
									...addPropertyOverrides(
										{
											c4QFbVLAH: {
												variant: "m2AGcC4bQ",
											},
											IBPTjmJqu: {
												variant: "m2AGcC4bQ",
											},
											lyejRH0mG: {
												variant: "m2AGcC4bQ",
											},
											PHdrEJxpc: {
												variant: "m2AGcC4bQ",
											},
											uLKAs1ePU: {
												variant: "m2AGcC4bQ",
											},
											YH5Zh04Gf: {
												variant: "m2AGcC4bQ",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={76}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
							{...addPropertyOverrides(
								{
									byIjNHLdI: {
										y: (componentViewport?.y || 0) + 76,
									},
									Fs5MnUuYF: {
										y: (componentViewport?.y || 0) + 0 + 152,
									},
									grc3Z8AOG: {
										y: (componentViewport?.y || 0) + 0 + 152,
									},
									IBPTjmJqu: {
										y: (componentViewport?.y || 0) + 0 + 152,
									},
									lyejRH0mG: {
										y: (componentViewport?.y || 0) + 0 + 152,
									},
									uLKAs1ePU: {
										y: (componentViewport?.y || 0) + 0 + 152,
									},
									YH5Zh04Gf: {
										y: (componentViewport?.y || 0) + 76,
									},
									zRG9ZrAis: {
										y: (componentViewport?.y || 0) + 0 + 152,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-gqwo7m-container"}
								data-framer-name={"Achievement 3"}
								layoutDependency={layoutDependency}
								layoutId={"Y6Rv4qT3a-container"}
								name={"Achievement 3"}
								nodeId={"Y6Rv4qT3a"}
								rendersWithMotion={true}
								scopeId={"wKxMV30eJ"}
								style={{
									opacity: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									Fs5MnUuYF: {
										opacity: 1,
									},
									grc3Z8AOG: {
										opacity: 1,
									},
									IBPTjmJqu: {
										opacity: 1,
									},
									lyejRH0mG: {
										opacity: 1,
									},
									uLKAs1ePU: {
										opacity: 1,
									},
									zRG9ZrAis: {
										opacity: 1,
									},
								}}
								{...addPropertyOverrides(
									{
										Fs5MnUuYF: {
											transformTemplate: void 0,
										},
										grc3Z8AOG: {
											transformTemplate: void 0,
										},
										IBPTjmJqu: {
											transformTemplate: void 0,
										},
										lyejRH0mG: {
											transformTemplate: void 0,
										},
										uLKAs1ePU: {
											transformTemplate: void 0,
										},
										zRG9ZrAis: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									BdUMN0rHF:
										"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
									ga_gk_gOP: "16px",
									height: "100%",
									id: "Y6Rv4qT3a",
									layoutId: "Y6Rv4qT3a",
									lpvxdnNhC: 0.6,
									name: "Achievement 3",
									style: {
										width: "100%",
									},
									UHOhwilMb: "95%",
									variant: "eohM_12uA",
									W0ThdLvu3:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									width: "100%",
									YsjACKB4l: "Client Satisfaction",
									...addPropertyOverrides(
										{
											c4QFbVLAH: {
												variant: "m2AGcC4bQ",
											},
											IBPTjmJqu: {
												variant: "m2AGcC4bQ",
											},
											lyejRH0mG: {
												variant: "m2AGcC4bQ",
											},
											PHdrEJxpc: {
												variant: "m2AGcC4bQ",
											},
											uLKAs1ePU: {
												variant: "m2AGcC4bQ",
											},
											YH5Zh04Gf: {
												variant: "m2AGcC4bQ",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={76}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
							{...addPropertyOverrides(
								{
									byIjNHLdI: {
										y: (componentViewport?.y || 0) + 76,
									},
									Fs5MnUuYF: {
										y: (componentViewport?.y || 0) + 0 + 228,
									},
									grc3Z8AOG: {
										y: (componentViewport?.y || 0) + 152,
									},
									IBPTjmJqu: {
										y: (componentViewport?.y || 0) + 0 + 228,
									},
									lyejRH0mG: {
										y: (componentViewport?.y || 0) + 152,
									},
									uLKAs1ePU: {
										y: (componentViewport?.y || 0) + 0 + 228,
									},
									YH5Zh04Gf: {
										y: (componentViewport?.y || 0) + 76,
									},
									zRG9ZrAis: {
										y: (componentViewport?.y || 0) + 0 + 228,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-7aouzb-container"}
								data-framer-name={"Achievement 4"}
								layoutDependency={layoutDependency}
								layoutId={"fazShX6xj-container"}
								name={"Achievement 4"}
								nodeId={"fazShX6xj"}
								rendersWithMotion={true}
								scopeId={"wKxMV30eJ"}
								style={{
									opacity: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									Fs5MnUuYF: {
										opacity: 1,
									},
									IBPTjmJqu: {
										opacity: 1,
									},
									uLKAs1ePU: {
										opacity: 1,
									},
									zRG9ZrAis: {
										opacity: 1,
									},
								}}
								{...addPropertyOverrides(
									{
										Fs5MnUuYF: {
											transformTemplate: void 0,
										},
										IBPTjmJqu: {
											transformTemplate: void 0,
										},
										uLKAs1ePU: {
											transformTemplate: void 0,
										},
										zRG9ZrAis: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									BdUMN0rHF:
										"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
									ga_gk_gOP: "16px",
									height: "100%",
									id: "fazShX6xj",
									layoutId: "fazShX6xj",
									lpvxdnNhC: 0.8,
									name: "Achievement 4",
									style: {
										width: "100%",
									},
									UHOhwilMb: "50+",
									variant: "eohM_12uA",
									W0ThdLvu3:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									width: "100%",
									YsjACKB4l: "Brands Transformed",
									...addPropertyOverrides(
										{
											c4QFbVLAH: {
												variant: "m2AGcC4bQ",
											},
											IBPTjmJqu: {
												variant: "m2AGcC4bQ",
											},
											lyejRH0mG: {
												variant: "m2AGcC4bQ",
											},
											PHdrEJxpc: {
												variant: "m2AGcC4bQ",
											},
											uLKAs1ePU: {
												variant: "m2AGcC4bQ",
											},
											YH5Zh04Gf: {
												variant: "m2AGcC4bQ",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={76}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
							{...addPropertyOverrides(
								{
									byIjNHLdI: {
										y: (componentViewport?.y || 0) + 76,
									},
									Fs5MnUuYF: {
										y: (componentViewport?.y || 0) + 0 + 304,
									},
									grc3Z8AOG: {
										y: (componentViewport?.y || 0) + 152,
									},
									IBPTjmJqu: {
										y: (componentViewport?.y || 0) + 0 + 304,
									},
									lyejRH0mG: {
										y: (componentViewport?.y || 0) + 152,
									},
									uLKAs1ePU: {
										y: (componentViewport?.y || 0) + 228,
									},
									YH5Zh04Gf: {
										y: (componentViewport?.y || 0) + 76,
									},
									zRG9ZrAis: {
										y: (componentViewport?.y || 0) + 228,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1mm0id3-container"}
								data-framer-name={"Achievement 5"}
								layoutDependency={layoutDependency}
								layoutId={"OaYAG0anU-container"}
								name={"Achievement 5"}
								nodeId={"OaYAG0anU"}
								rendersWithMotion={true}
								scopeId={"wKxMV30eJ"}
								style={{
									opacity: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									Fs5MnUuYF: {
										opacity: 1,
									},
									IBPTjmJqu: {
										opacity: 1,
									},
								}}
								{...addPropertyOverrides(
									{
										Fs5MnUuYF: {
											transformTemplate: void 0,
										},
										IBPTjmJqu: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{_jsx(stdin_default, {
									BdUMN0rHF:
										"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
									ga_gk_gOP: "16px",
									height: "100%",
									id: "OaYAG0anU",
									layoutId: "OaYAG0anU",
									lpvxdnNhC: 1,
									name: "Achievement 5",
									style: {
										width: "100%",
									},
									UHOhwilMb: "300+",
									variant: "eohM_12uA",
									W0ThdLvu3:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									width: "100%",
									YsjACKB4l: "Design Concepts Explored",
									...addPropertyOverrides(
										{
											c4QFbVLAH: {
												variant: "m2AGcC4bQ",
											},
											IBPTjmJqu: {
												variant: "m2AGcC4bQ",
											},
											lyejRH0mG: {
												variant: "m2AGcC4bQ",
											},
											PHdrEJxpc: {
												variant: "m2AGcC4bQ",
											},
											uLKAs1ePU: {
												variant: "m2AGcC4bQ",
											},
											YH5Zh04Gf: {
												variant: "m2AGcC4bQ",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-1ULUj.framer-1m1qv2k, .framer-1ULUj .framer-1m1qv2k { display: block; }",
	".framer-1ULUj.framer-77ms3x { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 546px; }",
	".framer-1ULUj .framer-1uiekmj-container { flex: none; height: auto; left: 0px; position: absolute; top: 0px; width: auto; z-index: 1; }",
	".framer-1ULUj .framer-817nyp-container { flex: none; height: auto; position: relative; width: 100%; z-index: 5; }",
	".framer-1ULUj .framer-1tsbq36-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; z-index: 4; }",
	".framer-1ULUj .framer-gqwo7m-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; z-index: 3; }",
	".framer-1ULUj .framer-7aouzb-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; z-index: 2; }",
	".framer-1ULUj .framer-1mm0id3-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: 100%; z-index: 1; }",
	".framer-1ULUj.framer-v-nga46w .framer-1tsbq36-container, .framer-1ULUj.framer-v-ayx20f .framer-1tsbq36-container, .framer-1ULUj.framer-v-ayx20f .framer-gqwo7m-container, .framer-1ULUj.framer-v-3810q0 .framer-1tsbq36-container, .framer-1ULUj.framer-v-3810q0 .framer-gqwo7m-container, .framer-1ULUj.framer-v-3810q0 .framer-7aouzb-container, .framer-1ULUj.framer-v-iotgh2 .framer-1tsbq36-container, .framer-1ULUj.framer-v-iotgh2 .framer-gqwo7m-container, .framer-1ULUj.framer-v-iotgh2 .framer-7aouzb-container, .framer-1ULUj.framer-v-iotgh2 .framer-1mm0id3-container, .framer-1ULUj.framer-v-1d0cg17 .framer-1tsbq36-container, .framer-1ULUj.framer-v-vaffwg .framer-1tsbq36-container, .framer-1ULUj.framer-v-vaffwg .framer-gqwo7m-container, .framer-1ULUj.framer-v-1386qk9 .framer-1tsbq36-container, .framer-1ULUj.framer-v-1386qk9 .framer-gqwo7m-container, .framer-1ULUj.framer-v-1386qk9 .framer-7aouzb-container, .framer-1ULUj.framer-v-1lebkyx .framer-1tsbq36-container, .framer-1ULUj.framer-v-1lebkyx .framer-gqwo7m-container, .framer-1ULUj.framer-v-1lebkyx .framer-7aouzb-container, .framer-1ULUj.framer-v-1lebkyx .framer-1mm0id3-container { left: unset; position: relative; top: unset; }",
	".framer-1ULUj.framer-v-nga46w .framer-gqwo7m-container, .framer-1ULUj.framer-v-nga46w .framer-7aouzb-container, .framer-1ULUj.framer-v-nga46w .framer-1mm0id3-container, .framer-1ULUj.framer-v-1d0cg17 .framer-gqwo7m-container, .framer-1ULUj.framer-v-1d0cg17 .framer-7aouzb-container, .framer-1ULUj.framer-v-1d0cg17 .framer-1mm0id3-container { top: 76px; }",
	".framer-1ULUj.framer-v-ayx20f .framer-7aouzb-container, .framer-1ULUj.framer-v-ayx20f .framer-1mm0id3-container, .framer-1ULUj.framer-v-vaffwg .framer-7aouzb-container, .framer-1ULUj.framer-v-vaffwg .framer-1mm0id3-container { top: 152px; }",
	".framer-1ULUj.framer-v-3810q0 .framer-1mm0id3-container, .framer-1ULUj.framer-v-1386qk9 .framer-1mm0id3-container { top: 228px; }",
	".framer-1ULUj.framer-v-35ac92.framer-77ms3x, .framer-1ULUj.framer-v-yr7qxp.framer-77ms3x, .framer-1ULUj.framer-v-1d0cg17.framer-77ms3x, .framer-1ULUj.framer-v-vaffwg.framer-77ms3x, .framer-1ULUj.framer-v-1386qk9.framer-77ms3x, .framer-1ULUj.framer-v-1lebkyx.framer-77ms3x { width: 350px; }",
];
var FramerwKxMV30eJ = withCSS(Component, css, "framer-1ULUj");
var stdin_default2 = FramerwKxMV30eJ;
FramerwKxMV30eJ.displayName = "Achievement Cards (Animated)";
FramerwKxMV30eJ.defaultProps = {
	height: 76,
	width: 546,
};
addPropertyControls(FramerwKxMV30eJ, {
	variant: {
		options: [
			"iKjmMWeqB",
			"S7qwU261K",
			"byIjNHLdI",
			"grc3Z8AOG",
			"zRG9ZrAis",
			"Fs5MnUuYF",
			"c4QFbVLAH",
			"PHdrEJxpc",
			"YH5Zh04Gf",
			"lyejRH0mG",
			"uLKAs1ePU",
			"IBPTjmJqu",
		],
		optionTitles: [
			"Default - (Desktop + Tablet)",
			"1 - (Desktop + Tablet)",
			"2 - (Desktop + Tablet)",
			"3 - (Desktop + Tablet)",
			"4 - (Desktop + Tablet)",
			"5 - (Desktop + Tablet)",
			"Default - (Phone)",
			"1 - (Phone)",
			"2 - (Phone)",
			"3 - (Phone)",
			"4 - (Phone)",
			"5 - (Phone)",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerwKxMV30eJ,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LayoutJumpPreventerFonts,
		...AchievementCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:achievement-cards-animated
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "c4QFbVLAH",
	xl: "iKjmMWeqB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AchievementCardsAnimatedFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var achievement_cards_animated_default = ComponentWithRoot;
export { achievement_cards_animated_default as default };
