// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * year?: string // Year
 * logo?: {src: string, srcSet?: string, alt?: string} // Logo
 * title?: string // Title
 * subtitle?: string // Subtitle
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-JNO5WJBK.js";
import { stdin_default } from "./chunks/chunk-Z5QDOKR5.js";
import { className, css, fonts } from "./chunks/chunk-3XNB3BOA.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:award-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zndYU52dLQoCEh4NfrSx/xyjT8ls48FeCWapwDiMN/axxZYd8xQ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withVariantAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RichTextWithFX = withFX(RichText);
var LineAnimationFonts = getFonts(stdin_default);
var LineAnimationWithVariantAppearEffect =
	withVariantAppearEffect(stdin_default);
var cycleOrder = ["kyCvi_wFy", "niaAVs4oE", "HliZfSSE_"];
var serializationHash = "framer-BOzGW";
var variantClassNames = {
	HliZfSSE_: "framer-v-1ns1qke",
	kyCvi_wFy: "framer-v-5oyxlz",
	niaAVs4oE: "framer-v-g8g5hu",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var transition2 = {
	bounce: 0,
	delay: 0,
	duration: 1,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "kyCvi_wFy",
	Phone: "HliZfSSE_",
	Tablet: "niaAVs4oE",
};
var getProps = ({
	height,
	id,
	logo,
	subtitle,
	title,
	width,
	year,
	...props
}) => {
	return {
		...props,
		GMtYCYZYl: logo ?? props.GMtYCYZYl,
		hxRmpbapI: year ?? props.hxRmpbapI ?? "2025",
		lIvEbsNfj: title ?? props.lIvEbsNfj ?? "Best Branding Identity",
		pofacxrAR:
			subtitle ??
			props.pofacxrAR ??
			"Recognized for crafting a luxury fragrance brand identity that blended storytelling with timeless aesthetics.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "kyCvi_wFy",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		hxRmpbapI,
		GMtYCYZYl,
		lIvEbsNfj,
		pofacxrAR,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "kyCvi_wFy",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-5oyxlz",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"kyCvi_wFy"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								HliZfSSE_: {
									"data-framer-name": "Phone",
								},
								niaAVs4oE: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-6mqwq4"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"yEscbhlS8"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1vupgxd"}
								data-framer-name={"Year"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"KiiWWu_u5"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={hxRmpbapI}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-17e0ml2"}
										data-styles-preset={"Iwq8LBfrK"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
										}}
									>
										{"2025"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-1tqcqii"}
								data-framer-name={"Logo & Title"}
								layoutDependency={layoutDependency}
								layoutId={"aGRdlTUUf"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 48 + 0 + 0 + 0 + 0,
										),
										sizes: "64px",
										...toResponsiveImage(GMtYCYZYl),
									}}
									className={"framer-debyxf"}
									data-framer-name={"Logo"}
									layoutDependency={layoutDependency}
									layoutId={"g40jsynFB"}
									{...addPropertyOverrides(
										{
											HliZfSSE_: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															32 +
															0 +
															0 +
															49.6 +
															0 +
															0,
													),
													sizes: "64px",
													...toResponsiveImage(GMtYCYZYl),
												},
											},
											niaAVs4oE: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 40 + 0 + 0 + 0 + 0,
													),
													sizes: "64px",
													...toResponsiveImage(GMtYCYZYl),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<motion.div
									className={"framer-gcu1iq"}
									data-framer-name={"Title & Subtitle"}
									layoutDependency={layoutDependency}
									layoutId={"cjR8defid"}
								>
									<RichTextWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__fromCanvasComponent={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-27g1h4"}
										data-framer-name={"Title"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Yz0uSOac7"}
										style={{
											"--extracted-1eung3n":
												"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={lIvEbsNfj}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h4
												className={"framer-styles-preset-1sgo5u0"}
												data-styles-preset={"ZIdQnR8E6"}
												style={{
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
												}}
											>
												{"Best Branding Identity"}
											</motion.h4>
										</React.Fragment>
									</RichTextWithFX>
									<RichTextWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__fromCanvasComponent={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1lqfqwn"}
										data-framer-name={"Subtitle"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"xBTet6SJC"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={pofacxrAR}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-17e0ml2"}
												data-styles-preset={"Iwq8LBfrK"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
												}}
											>
												{
													"Recognized for crafting a luxury fragrance brand identity that blended storytelling with timeless aesthetics."
												}
											</motion.p>
										</React.Fragment>
									</RichTextWithFX>
								</motion.div>
							</motion.div>
						</motion.div>
						<ComponentViewportProvider
							height={1}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 222) -
								1
							}
							{...addPropertyOverrides(
								{
									HliZfSSE_: {
										y:
											(componentViewport?.y || 0) +
											(componentViewport?.height || 257) -
											1,
									},
									niaAVs4oE: {
										y:
											(componentViewport?.y || 0) +
											(componentViewport?.height || 232) -
											1,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-ph8hpq-container"}
								layoutDependency={layoutDependency}
								layoutId={"t_iSd_HgF-container"}
								nodeId={"t_iSd_HgF"}
								rendersWithMotion={true}
								scopeId={"axxZYd8xQ"}
							>
								<LineAnimationWithVariantAppearEffect
									__framer__animateOnce={false}
									__framer__obscuredVariantId={"E3eQCy4P8"}
									__framer__threshold={0.5}
									__framer__variantAppearEffectEnabled={true}
									__framer__visibleVariantId={"C9aO6eCCS"}
									height={"100%"}
									id={"t_iSd_HgF"}
									layoutId={"t_iSd_HgF"}
									nhvtjR0LA={
										"var(--token-5bb10796-193a-46db-ac69-0030f944c211, rgb(178, 201, 230))"
									}
									style={{
										height: "100%",
										width: "100%",
									}}
									variant={"E3eQCy4P8"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-BOzGW.framer-ofjkxg, .framer-BOzGW .framer-ofjkxg { display: block; }",
	".framer-BOzGW.framer-5oyxlz { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 48px 0px 48px 0px; position: relative; width: 744px; }",
	".framer-BOzGW .framer-6mqwq4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BOzGW .framer-1vupgxd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-BOzGW .framer-1tqcqii { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; max-width: 552px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-BOzGW .framer-debyxf { flex: none; height: 15px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 64px; }",
	".framer-BOzGW .framer-gcu1iq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BOzGW .framer-27g1h4, .framer-BOzGW .framer-1lqfqwn { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-BOzGW .framer-ph8hpq-container { bottom: 0px; flex: none; height: 1px; left: 0px; position: absolute; width: 100%; z-index: 1; }",
	".framer-BOzGW.framer-v-g8g5hu.framer-5oyxlz { padding: 40px 0px 40px 0px; width: 610px; }",
	".framer-BOzGW.framer-v-g8g5hu .framer-1tqcqii { max-width: 440px; }",
	".framer-BOzGW.framer-v-1ns1qke.framer-5oyxlz { padding: 32px 0px 32px 0px; width: 350px; }",
	".framer-BOzGW.framer-v-1ns1qke .framer-6mqwq4 { flex-direction: column; gap: 24px; justify-content: flex-start; }",
	".framer-BOzGW.framer-v-1ns1qke .framer-1tqcqii { flex: none; gap: 12px; max-width: unset; width: 100%; }",
	...css,
	...css2,
];
var FrameraxxZYd8xQ = withCSS(Component, css3, "framer-BOzGW");
var stdin_default2 = FrameraxxZYd8xQ;
FrameraxxZYd8xQ.displayName = "Award Card";
FrameraxxZYd8xQ.defaultProps = {
	height: 222,
	width: 744,
};
addPropertyControls(FrameraxxZYd8xQ, {
	variant: {
		options: ["kyCvi_wFy", "niaAVs4oE", "HliZfSSE_"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	hxRmpbapI: {
		defaultValue: "2025",
		displayTextArea: false,
		title: "Year",
		type: ControlType.String,
	},
	GMtYCYZYl: {
		title: "Logo",
		type: ControlType.ResponsiveImage,
	},
	lIvEbsNfj: {
		defaultValue: "Best Branding Identity",
		displayTextArea: true,
		title: "Title",
		type: ControlType.String,
	},
	pofacxrAR: {
		defaultValue:
			"Recognized for crafting a luxury fragrance brand identity that blended storytelling with timeless aesthetics.",
		displayTextArea: true,
		title: "Subtitle",
		type: ControlType.String,
	},
});
addFonts(
	FrameraxxZYd8xQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...LineAnimationFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:award-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "HliZfSSE_",
	md: "niaAVs4oE",
	xl: "kyCvi_wFy",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AwardCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var award_card_default = ComponentWithRoot;
export { award_card_default as default };
