// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * title?: string // Title
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-K27265EC.js";
import { stdin_default } from "./chunks/chunk-JUG523YA.js";
import "./chunks/chunk-3XNB3BOA.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:blog-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/xwesKwo8TSe5a2kVJDNY/EkrWnsyWMyJTZ7WFlICj/Q2JtoCnXx.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BlogHoverButtonFonts = getFonts(stdin_default);
var enabledGestures = {
	E1CJFP9X4: {
		pressed: true,
	},
	hMGgzMcyF: {
		hover: true,
	},
	t2AACmX8n: {
		hover: true,
	},
};
var cycleOrder = ["hMGgzMcyF", "t2AACmX8n", "E1CJFP9X4"];
var serializationHash = "framer-JfKHc";
var variantClassNames = {
	E1CJFP9X4: "framer-v-2va6lm",
	hMGgzMcyF: "framer-v-1xhbrfb",
	t2AACmX8n: "framer-v-iq2xvt",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var transition2 = {
	duration: 0,
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "hMGgzMcyF",
	Phone: "E1CJFP9X4",
	Tablet: "t2AACmX8n",
};
var getProps = ({ height, id, image, link, title, width, ...props }) => {
	return {
		...props,
		HqdKCX32F: link ?? props.HqdKCX32F,
		HtMRpCb72: image ??
			props.HtMRpCb72 ?? {
				pixelHeight: 1816,
				pixelWidth: 1816,
				src: "https://framerusercontent.com/images/vA8xat7xbA0O6ZvtSwC8i4l20Cg.png?scale-down-to=1024&width=1816&height=1816",
				srcSet:
					"https://framerusercontent.com/images/vA8xat7xbA0O6ZvtSwC8i4l20Cg.png?scale-down-to=512&width=1816&height=1816 512w,https://framerusercontent.com/images/vA8xat7xbA0O6ZvtSwC8i4l20Cg.png?scale-down-to=1024&width=1816&height=1816 1024w,https://framerusercontent.com/images/vA8xat7xbA0O6ZvtSwC8i4l20Cg.png?width=1816&height=1816 1816w",
			},
		o9Fmxtywe:
			title ??
			props.o9Fmxtywe ??
			"Design Beyond Aesthetics: How Strategy Shapes Meaningful Brands",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "hMGgzMcyF",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		HtMRpCb72,
		o9Fmxtywe,
		HqdKCX32F,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "hMGgzMcyF",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							E1CJFP9X4: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Link
						href={HqdKCX32F}
						motionChild={true}
						nodeId={"hMGgzMcyF"}
						openInNewTab={false}
						scopeId={"Q2JtoCnXx"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1xhbrfb", className2, classNames)} framer-61hcqr`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"hMGgzMcyF"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"E1CJFP9X4-pressed": {
										"data-framer-name": void 0,
									},
									"hMGgzMcyF-hover": {
										"data-framer-name": void 0,
									},
									"t2AACmX8n-hover": {
										"data-framer-name": void 0,
									},
									E1CJFP9X4: {
										"data-framer-name": "Phone",
									},
									t2AACmX8n: {
										"data-framer-name": "Tablet",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-39c7ww"}
								data-framer-name={"Image Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"np0N6jRXO"}
								style={{
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							>
								<Image
									as={"figure"}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 574) - 0 - 526) / 2 +
													0 +
													0) +
												0,
										),
										pixelHeight: 1816,
										pixelWidth: 1816,
										sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
										...toResponsiveImage(HtMRpCb72),
									}}
									className={"framer-ocepf7"}
									layoutDependency={layoutDependency}
									layoutId={"xTWOyz9I_"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
										filter: "none",
										WebkitFilter: "none",
									}}
									variants={{
										"E1CJFP9X4-pressed": {
											filter: "none",
											WebkitFilter: "none",
										},
										"hMGgzMcyF-hover": {
											filter: "blur(3px)",
											WebkitFilter: "blur(3px)",
										},
										"t2AACmX8n-hover": {
											filter: "none",
											WebkitFilter: "none",
										},
									}}
									{...addPropertyOverrides(
										{
											E1CJFP9X4: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 566) - 0 - 518) /
																2 +
																0 +
																0) +
															0,
													),
													pixelHeight: 1816,
													pixelWidth: 1816,
													sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
													...toResponsiveImage(HtMRpCb72),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<ComponentViewportProvider
									height={42}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 574) - 0 - 526) / 2 +
											0 +
											0) +
										206
									}
									{...addPropertyOverrides(
										{
											E1CJFP9X4: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 566) - 0 - 518) / 2 +
														0 +
														0) +
													206,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-4tix9w-container"}
										layoutDependency={layoutDependency}
										layoutId={"qrqBoa8fq-container"}
										nodeId={"qrqBoa8fq"}
										rendersWithMotion={true}
										scopeId={"Q2JtoCnXx"}
										style={{
											opacity: 0,
											scale: 0,
										}}
										transformTemplate={transformTemplate1}
										variants={{
											"hMGgzMcyF-hover": {
												opacity: 1,
												scale: 1,
											},
											"t2AACmX8n-hover": {
												opacity: 1,
												scale: 1,
											},
										}}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "qrqBoa8fq",
											layoutId: "qrqBoa8fq",
											variant: "uKpsXojSD",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1gpxk43"}
								data-framer-name={"Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"nu5dQ86D8"}
								style={{
									"--extracted-a0htzi":
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={o9Fmxtywe}
								variants={{
									"E1CJFP9X4-pressed": {
										"--extracted-a0htzi":
											"var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25))",
									},
									"hMGgzMcyF-hover": {
										"--extracted-a0htzi":
											"var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25))",
									},
									"t2AACmX8n-hover": {
										"--extracted-a0htzi":
											"var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"E1CJFP9X4-pressed": {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-1oed8xl"}
														data-styles-preset={"h_gFfByM_"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25)))",
														}}
													>
														{
															"Design Beyond Aesthetics: How Strategy Shapes Meaningful Brands"
														}
													</motion.h3>
												</React.Fragment>
											),
										},
										"hMGgzMcyF-hover": {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-1oed8xl"}
														data-styles-preset={"h_gFfByM_"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25)))",
														}}
													>
														{
															"Design Beyond Aesthetics: How Strategy Shapes Meaningful Brands"
														}
													</motion.h3>
												</React.Fragment>
											),
										},
										"t2AACmX8n-hover": {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-1oed8xl"}
														data-styles-preset={"h_gFfByM_"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25)))",
														}}
													>
														{
															"Design Beyond Aesthetics: How Strategy Shapes Meaningful Brands"
														}
													</motion.h3>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-1oed8xl"}
										data-styles-preset={"h_gFfByM_"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
										}}
									>
										{
											"Design Beyond Aesthetics: How Strategy Shapes Meaningful Brands"
										}
									</motion.h3>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JfKHc.framer-61hcqr, .framer-JfKHc .framer-61hcqr { display: block; }",
	".framer-JfKHc.framer-1xhbrfb { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: 454px; }",
	".framer-JfKHc .framer-39c7ww { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-JfKHc .framer-ocepf7 { aspect-ratio: 1 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 454px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-JfKHc .framer-4tix9w-container { flex: none; height: auto; left: 50%; position: absolute; top: 50%; width: auto; z-index: 1; }",
	".framer-JfKHc .framer-1gpxk43 { flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-JfKHc.framer-v-2va6lm.framer-1xhbrfb { gap: 16px; }",
	...css,
];
var FramerQ2JtoCnXx = withCSS(Component, css2, "framer-JfKHc");
var stdin_default2 = FramerQ2JtoCnXx;
FramerQ2JtoCnXx.displayName = "Blog Card";
FramerQ2JtoCnXx.defaultProps = {
	height: 574,
	width: 454,
};
addPropertyControls(FramerQ2JtoCnXx, {
	variant: {
		options: ["hMGgzMcyF", "t2AACmX8n", "E1CJFP9X4"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	HtMRpCb72: {
		__defaultAssetReference:
			"data:framer/asset-reference,vA8xat7xbA0O6ZvtSwC8i4l20Cg.png?originalFilename=Blog+Img+index+1.png&width=1816&height=1816",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	o9Fmxtywe: {
		defaultValue:
			"Design Beyond Aesthetics: How Strategy Shapes Meaningful Brands",
		displayTextArea: true,
		title: "Title",
		type: ControlType.String,
	},
	HqdKCX32F: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerQ2JtoCnXx,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BlogHoverButtonFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:blog-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "E1CJFP9X4",
	xl: "hMGgzMcyF",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlogCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var blog_card_default = ComponentWithRoot;
export { blog_card_default as default };
