// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop - 1' | 'Desktop - 2' | 'Desktop - 3' | 'Tablet - 1' | 'Tablet - 2' | 'Tablet - 3' | 'Phone - 1' | 'Phone - 2' | 'Phone - 3' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-5P4TPMTP.js";
import "./chunks/chunk-JNO5WJBK.js";
import "./chunks/chunk-WT3LSARI.js";
import { stdin_default } from "./chunks/chunk-JZJLK5YE.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:case-study-hero-animated
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/v11CBNJ9LIaKrwkk7w3n/LILCg95Ou8I1wCrbzkTG/NOQTTcaif.js
import { jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	PathVariablesContext,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useQueryData,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CaseStudyCardHeroSmallFonts = getFonts(stdin_default2);
var cycleOrder = [
	"vKgAZ6lDa",
	"EovOzYAD7",
	"PchWerscy",
	"OVRv5Pk8K",
	"ut6OqfJwV",
	"ITBGBOUeD",
	"I36mDgamF",
	"h8le02ckZ",
	"UsWW_mUYw",
];
var serializationHash = "framer-qxqSR";
var variantClassNames = {
	EovOzYAD7: "framer-v-e44krq",
	h8le02ckZ: "framer-v-21ckw2",
	I36mDgamF: "framer-v-1i7qasj",
	ITBGBOUeD: "framer-v-you0xy",
	OVRv5Pk8K: "framer-v-gvliei",
	PchWerscy: "framer-v-6k9mdn",
	UsWW_mUYw: "framer-v-h0i3nq",
	ut6OqfJwV: "framer-v-1h3t245",
	vKgAZ6lDa: "framer-v-eif2sv",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 1,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var QueryData = ({ query: query3, pageSize, children }) => {
	const data = useQueryData(query3);
	return children(data);
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop - 1": "vKgAZ6lDa",
	"Desktop - 2": "EovOzYAD7",
	"Desktop - 3": "PchWerscy",
	"Phone - 1": "I36mDgamF",
	"Phone - 2": "h8le02ckZ",
	"Phone - 3": "UsWW_mUYw",
	"Tablet - 1": "OVRv5Pk8K",
	"Tablet - 2": "ut6OqfJwV",
	"Tablet - 3": "ITBGBOUeD",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "vKgAZ6lDa",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		enWG8r4k9D8ByPCDkr,
		ERzIvOemLD8ByPCDkr,
		R7zDmu9UhD8ByPCDkr,
		idD8ByPCDkr,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "vKgAZ6lDa",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear19mjjiv = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("EovOzYAD7", true), 3e3);
	});
	const onAppear77p0x = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("PchWerscy", true), 3e3);
	});
	const onAppear1myovsj = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("vKgAZ6lDa", true), 3e3);
	});
	const onAppearvjrhvp = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("ut6OqfJwV", true), 3e3);
	});
	const onAppearo2d8g0 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("ITBGBOUeD", true), 3e3);
	});
	const onAppearl5elbe = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("OVRv5Pk8K", true), 3e3);
	});
	const onAppearybyp3v = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("h8le02ckZ", true), 3e3);
	});
	const onAppear1jie41u = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("UsWW_mUYw", true), 3e3);
	});
	const onAppear1crcyg5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("I36mDgamF", true), 3e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear19mjjiv,
		EovOzYAD7: onAppear77p0x,
		h8le02ckZ: onAppear1jie41u,
		I36mDgamF: onAppearybyp3v,
		ITBGBOUeD: onAppearl5elbe,
		OVRv5Pk8K: onAppearvjrhvp,
		PchWerscy: onAppear1myovsj,
		UsWW_mUYw: onAppear1crcyg5,
		ut6OqfJwV: onAppearo2d8g0,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-eif2sv",
							className,
							classNames,
						)}
						data-framer-name={"Desktop - 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"vKgAZ6lDa"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								EovOzYAD7: {
									"data-framer-name": "Desktop - 2",
								},
								h8le02ckZ: {
									"data-framer-name": "Phone - 2",
								},
								I36mDgamF: {
									"data-framer-name": "Phone - 1",
								},
								ITBGBOUeD: {
									"data-framer-name": "Tablet - 3",
								},
								OVRv5Pk8K: {
									"data-framer-name": "Tablet - 1",
								},
								PchWerscy: {
									"data-framer-name": "Desktop - 3",
								},
								UsWW_mUYw: {
									"data-framer-name": "Phone - 3",
								},
								ut6OqfJwV: {
									"data-framer-name": "Tablet - 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-rl0zxt"}
							layoutDependency={layoutDependency}
							layoutId={"D8ByPCDkr"}
						>
							<ChildrenCanSuspend>
								<QueryData
									query={{
										from: {
											alias: "D8ByPCDkr",
											data: stdin_default,
											type: "Collection",
										},
										limit: {
											type: "LiteralValue",
											value: 1,
										},
										offset: {
											type: "LiteralValue",
											value: 0,
										},
										select: [
											{
												collection: "D8ByPCDkr",
												name: "enWG8r4k9",
												type: "Identifier",
											},
											{
												collection: "D8ByPCDkr",
												name: "ERzIvOemL",
												type: "Identifier",
											},
											{
												collection: "D8ByPCDkr",
												name: "R7zDmu9Uh",
												type: "Identifier",
											},
											{
												collection: "D8ByPCDkr",
												name: "id",
												type: "Identifier",
											},
										],
									}}
									{...addPropertyOverrides(
										{
											EovOzYAD7: {
												query: {
													from: {
														alias: "D8ByPCDkr",
														data: stdin_default,
														type: "Collection",
													},
													limit: {
														type: "LiteralValue",
														value: 1,
													},
													offset: {
														type: "LiteralValue",
														value: 1,
													},
													select: [
														{
															collection: "D8ByPCDkr",
															name: "enWG8r4k9",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "ERzIvOemL",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "R7zDmu9Uh",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "id",
															type: "Identifier",
														},
													],
												},
											},
											h8le02ckZ: {
												query: {
													from: {
														alias: "D8ByPCDkr",
														data: stdin_default,
														type: "Collection",
													},
													limit: {
														type: "LiteralValue",
														value: 1,
													},
													offset: {
														type: "LiteralValue",
														value: 1,
													},
													select: [
														{
															collection: "D8ByPCDkr",
															name: "enWG8r4k9",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "ERzIvOemL",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "R7zDmu9Uh",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "id",
															type: "Identifier",
														},
													],
												},
											},
											ITBGBOUeD: {
												query: {
													from: {
														alias: "D8ByPCDkr",
														data: stdin_default,
														type: "Collection",
													},
													limit: {
														type: "LiteralValue",
														value: 1,
													},
													offset: {
														type: "LiteralValue",
														value: 2,
													},
													select: [
														{
															collection: "D8ByPCDkr",
															name: "enWG8r4k9",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "ERzIvOemL",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "R7zDmu9Uh",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "id",
															type: "Identifier",
														},
													],
												},
											},
											PchWerscy: {
												query: {
													from: {
														alias: "D8ByPCDkr",
														data: stdin_default,
														type: "Collection",
													},
													limit: {
														type: "LiteralValue",
														value: 1,
													},
													offset: {
														type: "LiteralValue",
														value: 2,
													},
													select: [
														{
															collection: "D8ByPCDkr",
															name: "enWG8r4k9",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "ERzIvOemL",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "R7zDmu9Uh",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "id",
															type: "Identifier",
														},
													],
												},
											},
											UsWW_mUYw: {
												query: {
													from: {
														alias: "D8ByPCDkr",
														data: stdin_default,
														type: "Collection",
													},
													limit: {
														type: "LiteralValue",
														value: 1,
													},
													offset: {
														type: "LiteralValue",
														value: 2,
													},
													select: [
														{
															collection: "D8ByPCDkr",
															name: "enWG8r4k9",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "ERzIvOemL",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "R7zDmu9Uh",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "id",
															type: "Identifier",
														},
													],
												},
											},
											ut6OqfJwV: {
												query: {
													from: {
														alias: "D8ByPCDkr",
														data: stdin_default,
														type: "Collection",
													},
													limit: {
														type: "LiteralValue",
														value: 1,
													},
													offset: {
														type: "LiteralValue",
														value: 1,
													},
													select: [
														{
															collection: "D8ByPCDkr",
															name: "enWG8r4k9",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "ERzIvOemL",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "R7zDmu9Uh",
															type: "Identifier",
														},
														{
															collection: "D8ByPCDkr",
															name: "id",
															type: "Identifier",
														},
													],
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									{(collection, paginationInfo, loadMore) => (
										<_Fragment>
											{collection?.map(
												(
													{
														enWG8r4k9: enWG8r4k9D8ByPCDkr2,
														ERzIvOemL: ERzIvOemLD8ByPCDkr2,
														id: idD8ByPCDkr2,
														R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
													},
													index,
												) => {
													enWG8r4k9D8ByPCDkr2 ??= "";
													R7zDmu9UhD8ByPCDkr2 ??= "";
													return (
														<LayoutGroup id={`D8ByPCDkr-${idD8ByPCDkr2}`}>
															<PathVariablesContext.Provider
																value={{
																	R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																}}
															>
																<ResolveLinks
																	links={[
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																		{
																			href: {
																				pathVariables: {
																					R7zDmu9Uh: R7zDmu9UhD8ByPCDkr2,
																				},
																				webPageId: "G37PM_8sm",
																			},
																			implicitPathVariables: void 0,
																		},
																	]}
																>
																	{(resolvedLinks) => (
																		<ComponentViewportProvider
																			height={192}
																			width={`max(${componentViewport?.width || "100vw"}, 1px)`}
																			y={
																				(componentViewport?.y || 0) +
																				(0 +
																					((componentViewport?.height || 192) -
																						0 -
																						192) /
																						2) +
																				0 +
																				0
																			}
																			{...addPropertyOverrides(
																				{
																					ITBGBOUeD: {
																						y:
																							(componentViewport?.y || 0) +
																							(0 +
																								((componentViewport?.height ||
																									170) -
																									0 -
																									192) /
																									2) +
																							0 +
																							0,
																					},
																					OVRv5Pk8K: {
																						y:
																							(componentViewport?.y || 0) +
																							(0 +
																								((componentViewport?.height ||
																									170) -
																									0 -
																									192) /
																									2) +
																							0 +
																							0,
																					},
																					ut6OqfJwV: {
																						y:
																							(componentViewport?.y || 0) +
																							(0 +
																								((componentViewport?.height ||
																									170) -
																									0 -
																									192) /
																									2) +
																							0 +
																							0,
																					},
																				},
																				baseVariant,
																				gestureVariant,
																			)}
																		>
																			<SmartComponentScopedContainer
																				className={"framer-1ihj1ru-container"}
																				layoutDependency={layoutDependency}
																				layoutId={"vX7V98SpH-container"}
																				nodeId={"vX7V98SpH"}
																				rendersWithMotion={true}
																				scopeId={"NOQTTcaif"}
																			>
																				{_jsx(stdin_default2, {
																					GUCoTfXDQ: resolvedLinks[0],
																					height: "100%",
																					id: "vX7V98SpH",
																					layoutId: "vX7V98SpH",
																					RzTCSDldB:
																						toResponsiveImage(
																							ERzIvOemLD8ByPCDkr2,
																						),
																					style: {
																						width: "100%",
																					},
																					variant: "MFJAv8_Lk",
																					width: "100%",
																					ZRn72QnWD: enWG8r4k9D8ByPCDkr2,
																					...addPropertyOverrides(
																						{
																							EovOzYAD7: {
																								GUCoTfXDQ: resolvedLinks[1],
																							},
																							h8le02ckZ: {
																								GUCoTfXDQ: resolvedLinks[7],
																								variant: "K2eWAVayS",
																							},
																							I36mDgamF: {
																								GUCoTfXDQ: resolvedLinks[6],
																								variant: "K2eWAVayS",
																							},
																							ITBGBOUeD: {
																								GUCoTfXDQ: resolvedLinks[5],
																								variant: "SrMnKM5_V",
																							},
																							OVRv5Pk8K: {
																								GUCoTfXDQ: resolvedLinks[3],
																								variant: "SrMnKM5_V",
																							},
																							PchWerscy: {
																								GUCoTfXDQ: resolvedLinks[2],
																							},
																							UsWW_mUYw: {
																								GUCoTfXDQ: resolvedLinks[8],
																								variant: "K2eWAVayS",
																							},
																							ut6OqfJwV: {
																								GUCoTfXDQ: resolvedLinks[4],
																								variant: "SrMnKM5_V",
																							},
																						},
																						baseVariant,
																						gestureVariant,
																					),
																				})}
																			</SmartComponentScopedContainer>
																		</ComponentViewportProvider>
																	)}
																</ResolveLinks>
															</PathVariablesContext.Provider>
														</LayoutGroup>
													);
												},
											)}
										</_Fragment>
									)}
								</QueryData>
							</ChildrenCanSuspend>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-qxqSR.framer-3vtp04, .framer-qxqSR .framer-3vtp04 { display: block; }",
	".framer-qxqSR.framer-eif2sv { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 376px; }",
	".framer-qxqSR .framer-rl0zxt { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 1px; }",
	".framer-qxqSR .framer-1ihj1ru-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-qxqSR.framer-v-gvliei.framer-eif2sv, .framer-qxqSR.framer-v-1h3t245.framer-eif2sv, .framer-qxqSR.framer-v-you0xy.framer-eif2sv { width: 246px; }",
];
var FramerNOQTTcaif = withCSS(Component, css, "framer-qxqSR");
var stdin_default3 = FramerNOQTTcaif;
FramerNOQTTcaif.displayName = "Case Study - Hero (Animated)";
FramerNOQTTcaif.defaultProps = {
	height: 192,
	width: 376,
};
addPropertyControls(FramerNOQTTcaif, {
	variant: {
		options: [
			"vKgAZ6lDa",
			"EovOzYAD7",
			"PchWerscy",
			"OVRv5Pk8K",
			"ut6OqfJwV",
			"ITBGBOUeD",
			"I36mDgamF",
			"h8le02ckZ",
			"UsWW_mUYw",
		],
		optionTitles: [
			"Desktop - 1",
			"Desktop - 2",
			"Desktop - 3",
			"Tablet - 1",
			"Tablet - 2",
			"Tablet - 3",
			"Phone - 1",
			"Phone - 2",
			"Phone - 3",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerNOQTTcaif,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...CaseStudyCardHeroSmallFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:case-study-hero-animated
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "I36mDgamF",
	md: "ut6OqfJwV",
	xl: "EovOzYAD7",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CaseStudyHeroAnimatedFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var case_study_hero_animated_default = ComponentWithRoot;
export { case_study_hero_animated_default as default };
