// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' | 'Tablet' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * title?: string // Title
 * fill?: string // Fill
 * revealColor?: string // Reveal Color
 * link?: string // Link
}} Props

 */
import { stdin_default } from "./chunks/chunk-3EBJ6VI3.js";
import { className, css, fonts } from "./chunks/chunk-UOQGEBQU.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:case-study-card-latest-project
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/hklOyGZJSsH9mlHsSxCJ/EZMHCn2zNIzOY707vavn/KXejjIZja.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withVariantAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RevealOverlayCaseStudyImageFonts = getFonts(stdin_default);
var RevealOverlayCaseStudyImageWithVariantAppearEffect =
	withVariantAppearEffect(stdin_default);
var enabledGestures = {
	HxpPPyMFL: {
		hover: true,
	},
	uikeaiRgU: {
		hover: true,
	},
	Y24yVLtRt: {
		pressed: true,
	},
};
var cycleOrder = ["uikeaiRgU", "Y24yVLtRt", "HxpPPyMFL"];
var serializationHash = "framer-1AJMd";
var variantClassNames = {
	HxpPPyMFL: "framer-v-8eybbu",
	uikeaiRgU: "framer-v-1w7bmxf",
	Y24yVLtRt: "framer-v-1ixvlu5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 1,
	type: "spring",
};
var transition2 = {
	duration: 0,
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "uikeaiRgU",
	Phone: "Y24yVLtRt",
	Tablet: "HxpPPyMFL",
};
var getProps = ({
	fill,
	height,
	id,
	image,
	link,
	revealColor,
	title,
	width,
	...props
}) => {
	return {
		...props,
		CAwr5yT0G: link ?? props.CAwr5yT0G,
		EJWl63j7A:
			title ??
			props.EJWl63j7A ??
			"Crafting Orris\xE9: An Immersive Study in Fragrance Identity",
		N_I2f7e5z:
			fill ??
			props.N_I2f7e5z ??
			"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
		OWz75TK7w:
			revealColor ??
			props.OWz75TK7w ??
			"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
		sdL8lXHCa: image ?? props.sdL8lXHCa,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "uikeaiRgU",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		sdL8lXHCa,
		EJWl63j7A,
		N_I2f7e5z,
		OWz75TK7w,
		CAwr5yT0G,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "uikeaiRgU",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							Y24yVLtRt: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Link
						href={CAwr5yT0G}
						motionChild={true}
						nodeId={"uikeaiRgU"}
						openInNewTab={false}
						scopeId={"KXejjIZja"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1w7bmxf", className2, classNames)} framer-1urggwk`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"uikeaiRgU"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"HxpPPyMFL-hover": {
										"data-framer-name": void 0,
									},
									"uikeaiRgU-hover": {
										"data-framer-name": void 0,
									},
									"Y24yVLtRt-pressed": {
										"data-framer-name": void 0,
									},
									HxpPPyMFL: {
										"data-framer-name": "Tablet",
									},
									Y24yVLtRt: {
										"data-framer-name": "Phone",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1i97ypo"}
								data-framer-name={"Image Content"}
								layoutDependency={layoutDependency}
								layoutId={"p2eVFh2FN"}
								style={{
									backgroundColor: N_I2f7e5z,
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							>
								<motion.div
									className={"framer-p69jue"}
									data-framer-name={"Image Wrap"}
									layoutDependency={layoutDependency}
									layoutId={"TbIRp2WIy"}
									style={{
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
									}}
								>
									<Image
										as={"figure"}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 644) - 0 - 584) / 2 +
														0 +
														0) +
													28 +
													0 +
													0,
											),
											sizes: `max(${componentViewport?.width || "100vw"} - 56px, 1px)`,
											...toResponsiveImage(sdL8lXHCa),
										}}
										className={"framer-141ss3t"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"IeMUsMujz"}
										style={{
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
											rotate: 0,
											scale: 1,
										}}
										variants={{
											"HxpPPyMFL-hover": {
												rotate: 3,
												scale: 1.1,
											},
											"uikeaiRgU-hover": {
												rotate: 3,
												scale: 1.1,
											},
											"Y24yVLtRt-pressed": {
												rotate: 0,
												scale: 1,
											},
										}}
										{...addPropertyOverrides(
											{
												HxpPPyMFL: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 646) -
																	0 -
																	568) /
																	2 +
																	0 +
																	0) +
																20 +
																0 +
																0,
														),
														sizes: `max(${componentViewport?.width || "100vw"} - 40px, 1px)`,
														...toResponsiveImage(sdL8lXHCa),
													},
												},
												Y24yVLtRt: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 639) -
																	0 -
																	552) /
																	2 +
																	0 +
																	0) +
																16 +
																0 +
																0,
														),
														sizes: `max(${componentViewport?.width || "100vw"} - 32px, 1px)`,
														...toResponsiveImage(sdL8lXHCa),
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<ComponentViewportProvider
										height={444}
										width={`calc(${componentViewport?.width || "100vw"} - 56px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 644) - 0 - 584) / 2 +
												0 +
												0) +
											28 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												HxpPPyMFL: {
													width: `calc(${componentViewport?.width || "100vw"} - 40px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 646) - 0 - 568) /
															2 +
															0 +
															0) +
														20 +
														0 +
														0,
												},
												Y24yVLtRt: {
													width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 639) - 0 - 552) /
															2 +
															0 +
															0) +
														16 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1ize3a2-container"}
											layoutDependency={layoutDependency}
											layoutId={"Nma8PQTUg-container"}
											nodeId={"Nma8PQTUg"}
											rendersWithMotion={true}
											scopeId={"KXejjIZja"}
										>
											<RevealOverlayCaseStudyImageWithVariantAppearEffect
												__framer__animateOnce={true}
												__framer__obscuredVariantId={"qpwAhlJZm"}
												__framer__threshold={0.5}
												__framer__variantAppearEffectEnabled={true}
												__framer__visibleVariantId={"ZKMbXQYPw"}
												height={"100%"}
												id={"Nma8PQTUg"}
												layoutId={"Nma8PQTUg"}
												style={{
													height: "100%",
													width: "100%",
												}}
												tu3vRje3v={OWz75TK7w}
												variant={"qpwAhlJZm"}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1qhrv03"}
								data-framer-name={"Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"VeAcwQ6gw"}
								style={{
									"--extracted-1of0zx5":
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={EJWl63j7A}
								variants={{
									"HxpPPyMFL-hover": {
										"--extracted-1of0zx5":
											"var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25))",
									},
									"uikeaiRgU-hover": {
										"--extracted-1of0zx5":
											"var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25))",
									},
									"Y24yVLtRt-pressed": {
										"--extracted-1of0zx5":
											"var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"HxpPPyMFL-hover": {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-pyrh9q"}
														data-styles-preset={"RXS0p1P3P"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25)))",
														}}
													>
														{
															"Crafting Orris\xE9: An Immersive Study in Fragrance Identity"
														}
													</motion.h2>
												</React.Fragment>
											),
										},
										"uikeaiRgU-hover": {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-pyrh9q"}
														data-styles-preset={"RXS0p1P3P"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25)))",
														}}
													>
														{
															"Crafting Orris\xE9: An Immersive Study in Fragrance Identity"
														}
													</motion.h2>
												</React.Fragment>
											),
										},
										"Y24yVLtRt-pressed": {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-pyrh9q"}
														data-styles-preset={"RXS0p1P3P"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--token-884a8452-aedf-4a14-a0db-a452e5d2a821, rgb(228, 70, 25)))",
														}}
													>
														{
															"Crafting Orris\xE9: An Immersive Study in Fragrance Identity"
														}
													</motion.h2>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h2
										className={"framer-styles-preset-pyrh9q"}
										data-styles-preset={"RXS0p1P3P"}
										style={{
											"--framer-text-color":
												"var(--extracted-1of0zx5, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
										}}
									>
										{
											"Crafting Orris\xE9: An Immersive Study in Fragrance Identity"
										}
									</motion.h2>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-1AJMd.framer-1urggwk, .framer-1AJMd .framer-1urggwk { display: block; }",
	".framer-1AJMd.framer-1w7bmxf { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: 456px; }",
	".framer-1AJMd .framer-1i97ypo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 28px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-1AJMd .framer-p69jue { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-1AJMd .framer-141ss3t { aspect-ratio: 0.9009009009009009 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 444px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-1AJMd .framer-1ize3a2-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-1AJMd .framer-1qhrv03 { flex: none; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-1AJMd.framer-v-1ixvlu5.framer-1w7bmxf { gap: 16px; }",
	".framer-1AJMd.framer-v-1ixvlu5 .framer-1i97ypo { padding: 16px; }",
	".framer-1AJMd.framer-v-1ixvlu5 .framer-141ss3t { height: var(--framer-aspect-ratio-supported, 471px); }",
	".framer-1AJMd.framer-v-8eybbu .framer-1i97ypo { padding: 20px; }",
	".framer-1AJMd.framer-v-8eybbu .framer-141ss3t { height: var(--framer-aspect-ratio-supported, 462px); }",
	...css,
];
var FramerKXejjIZja = withCSS(Component, css2, "framer-1AJMd");
var stdin_default2 = FramerKXejjIZja;
FramerKXejjIZja.displayName = "Case Study Card (Latest Project)";
FramerKXejjIZja.defaultProps = {
	height: 644,
	width: 456,
};
addPropertyControls(FramerKXejjIZja, {
	variant: {
		options: ["uikeaiRgU", "Y24yVLtRt", "HxpPPyMFL"],
		optionTitles: ["Desktop", "Phone", "Tablet"],
		title: "Variant",
		type: ControlType.Enum,
	},
	sdL8lXHCa: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	EJWl63j7A: {
		defaultValue:
			"Crafting Orris\xE9: An Immersive Study in Fragrance Identity",
		displayTextArea: true,
		title: "Title",
		type: ControlType.String,
	},
	N_I2f7e5z: {
		defaultValue:
			'var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)) /* {"name":"Primary"} */',
		title: "Fill",
		type: ControlType.Color,
	},
	OWz75TK7w: {
		defaultValue:
			'var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)) /* {"name":"Primary"} */',
		title: "Reveal Color",
		type: ControlType.Color,
	},
	CAwr5yT0G: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerKXejjIZja,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...RevealOverlayCaseStudyImageFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:case-study-card-latest-project
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Y24yVLtRt",
	xl: "uikeaiRgU",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CaseStudyCardLatestProjectFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var case_study_card_latest_project_default = ComponentWithRoot;
export { case_study_card_latest_project_default as default };
