// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-2O2LT7PK.js";
import { stdin_default } from "./chunks/chunk-3EBJ6VI3.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UOQGEBQU.js";
import { className, css, fonts } from "./chunks/chunk-3XNB3BOA.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:case-study-card-large
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/55qZItDhAkJV4JSmsPMx/0ISkrhqx6OaVh3O6fAO3/B6STIL4OB.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withVariantAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ButtonSecondaryLargeFonts = getFonts(stdin_default2);
var RevealOverlayCaseStudyImageFonts = getFonts(stdin_default);
var RevealOverlayCaseStudyImageWithVariantAppearEffect =
	withVariantAppearEffect(stdin_default);
var enabledGestures = {
	avM34QCdd: {
		pressed: true,
	},
	fTqfa6zMT: {
		hover: true,
	},
	NWAjxHYDL: {
		hover: true,
	},
};
var cycleOrder = ["fTqfa6zMT", "NWAjxHYDL", "avM34QCdd"];
var serializationHash = "framer-65xmp";
var variantClassNames = {
	avM34QCdd: "framer-v-1k8kvqk",
	fTqfa6zMT: "framer-v-cfg330",
	NWAjxHYDL: "framer-v-uuvr0z",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var xrSCR6TM6 = void 0;
var rbq5yS_jg = void 0;
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 1,
	type: "spring",
};
var transition2 = {
	duration: 0,
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "fTqfa6zMT",
	Phone: "avM34QCdd",
	Tablet: "NWAjxHYDL",
};
var getProps = ({
	bGFill,
	cardImage,
	height,
	id,
	link,
	projectType,
	title,
	width,
	year,
	...props
}) => {
	return {
		...props,
		At4Pr3rJk: year ?? props.At4Pr3rJk ?? "2025",
		Hp5TV0EJT: cardImage ??
			props.Hp5TV0EJT ?? {
				pixelHeight: 1776,
				pixelWidth: 1296,
				src: "https://framerusercontent.com/images/BYrxPxIvmunBK4mrRB4kWpT1pUs.png?width=1296&height=1776",
				srcSet:
					"https://framerusercontent.com/images/BYrxPxIvmunBK4mrRB4kWpT1pUs.png?scale-down-to=1024&width=1296&height=1776 747w,https://framerusercontent.com/images/BYrxPxIvmunBK4mrRB4kWpT1pUs.png?width=1296&height=1776 1296w",
			},
		Os6cY3CKf:
			title ??
			props.Os6cY3CKf ??
			"Crafting Orris\xE9: An Immersive Study in Fragrance Identity",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fTqfa6zMT",
		wprkFfBdg: link ?? props.wprkFfBdg,
		xaGbPDv6W: projectType ?? props.xaGbPDv6W ?? "Branding",
		XiSILjU_N:
			bGFill ??
			props.XiSILjU_N ??
			"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		At4Pr3rJk: At4Pr3rJk2,
		xaGbPDv6W: xaGbPDv6W2,
		Os6cY3CKf: Os6cY3CKf2,
		Hp5TV0EJT: Hp5TV0EJT2,
		XiSILjU_N: XiSILjU_N2,
		wprkFfBdg: wprkFfBdg2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fTqfa6zMT",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							avM34QCdd: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Link
						href={wprkFfBdg2}
						motionChild={true}
						nodeId={"fTqfa6zMT"}
						openInNewTab={false}
						scopeId={"B6STIL4OB"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-cfg330", className3, classNames)} framer-1e1xotk`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"fTqfa6zMT"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"avM34QCdd-pressed": {
										"data-framer-name": void 0,
									},
									"fTqfa6zMT-hover": {
										"data-framer-name": void 0,
									},
									"NWAjxHYDL-hover": {
										"data-framer-name": void 0,
									},
									avM34QCdd: {
										"data-framer-name": "Phone",
									},
									NWAjxHYDL: {
										"data-framer-name": "Tablet",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-jzjwbx"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"YPMSAA3Hx"}
								style={{
									backgroundColor: XiSILjU_N2,
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							>
								<motion.div
									className={"framer-ps7uzi"}
									data-framer-name={"Text Content"}
									layoutDependency={layoutDependency}
									layoutId={"ZEv2igCQ8"}
								>
									<motion.div
										className={"framer-1vjd27a"}
										data-framer-name={"Tag & Title"}
										layoutDependency={layoutDependency}
										layoutId={"y54MKicAB"}
									>
										<motion.div
											className={"framer-utmw43"}
											data-framer-name={"Tag Wrap"}
											layoutDependency={layoutDependency}
											layoutId={"vf8QvW4jd"}
										>
											<motion.div
												className={"framer-lg596a"}
												data-border={true}
												data-framer-name={"Year"}
												layoutDependency={layoutDependency}
												layoutId={"NNRuqR46o"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color":
														"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
													borderBottomLeftRadius: 32,
													borderBottomRightRadius: 32,
													borderTopLeftRadius: 32,
													borderTopRightRadius: 32,
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-mntxjh"}
													data-framer-name={"Year"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"MCqcNzvvG"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
														"--framer-paragraph-spacing": "0px",
													}}
													text={At4Pr3rJk2}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-17e0ml2"}
															data-styles-preset={"Iwq8LBfrK"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
															}}
														>
															{"2025"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-kh731f"}
												data-border={true}
												data-framer-name={"Project Type"}
												layoutDependency={layoutDependency}
												layoutId={"GliXZuaI3"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color":
														"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
													borderBottomLeftRadius: 32,
													borderBottomRightRadius: 32,
													borderTopLeftRadius: 32,
													borderTopRightRadius: 32,
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-mj9knu"}
													data-framer-name={"Project Type"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"DaRnTApqQ"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
														"--framer-paragraph-spacing": "0px",
													}}
													text={xaGbPDv6W2}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-17e0ml2"}
															data-styles-preset={"Iwq8LBfrK"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
															}}
														>
															{"Branding"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										</motion.div>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-s3svm2"}
											data-framer-name={"Title"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"i_Ghs6C0S"}
											style={{
												"--extracted-1of0zx5":
													"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
												"--framer-paragraph-spacing": "0px",
											}}
											text={Os6cY3CKf2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h2
													className={"framer-styles-preset-pyrh9q"}
													data-styles-preset={"RXS0p1P3P"}
													style={{
														"--framer-text-color":
															"var(--extracted-1of0zx5, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
													}}
												>
													{
														"Crafting Orris\xE9: An Immersive Study in Fragrance Identity"
													}
												</motion.h2>
											</React.Fragment>
										</RichText>
									</motion.div>
									<ComponentViewportProvider
										height={26}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 436) - 0 - 436) / 2) +
											28 +
											20 +
											314
										}
										{...addPropertyOverrides(
											{
												"avM34QCdd-pressed": {
													y: void 0,
												},
												avM34QCdd: {
													y: void 0,
												},
												NWAjxHYDL: {
													y:
														(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 325) - 0 - 420) /
																2) +
														20 +
														16 +
														322,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-ojqf01-container"}
											layoutDependency={layoutDependency}
											layoutId={"U5Sv7k8zk-container"}
											nodeId={"U5Sv7k8zk"}
											rendersWithMotion={true}
											scopeId={"B6STIL4OB"}
										>
											{_jsx(stdin_default2, {
												DuT5vp6qA: "SEE PROJECT",
												height: "100%",
												id: "U5Sv7k8zk",
												layoutId: "U5Sv7k8zk",
												variant: "qcO2spiRi",
												width: "100%",
												...addPropertyOverrides(
													{
														"avM34QCdd-pressed": {
															variant: rbq5yS_jg,
														},
														"fTqfa6zMT-hover": {
															variant: xrSCR6TM6,
														},
														"NWAjxHYDL-hover": {
															variant: xrSCR6TM6,
														},
														avM34QCdd: {
															variant: "uRXIPSv2M",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-xaqtgw"}
									data-framer-name={"Image Wrap"}
									layoutDependency={layoutDependency}
									layoutId={"wlhUVJV45"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
								>
									<Image
										as={"figure"}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 436) - 0 - 436) /
															2) +
													28 +
													0,
											),
											pixelHeight: 1776,
											pixelWidth: 1296,
											sizes: `max(min(max((max(${componentViewport?.width || "100vw"}, 1px) - 56px) / 2.716 - 10px, 1px), 324px), 1px)`,
											...toResponsiveImage(Hp5TV0EJT2),
										}}
										className={"framer-1dwb00q"}
										layoutDependency={layoutDependency}
										layoutId={"IqBPEZnt7"}
										style={{
											rotate: 0,
											scale: 1,
										}}
										variants={{
											"avM34QCdd-pressed": {
												rotate: 0,
												scale: 1,
											},
											"fTqfa6zMT-hover": {
												rotate: 3,
												scale: 1.1,
											},
											"NWAjxHYDL-hover": {
												rotate: 3,
												scale: 1.1,
											},
										}}
										{...addPropertyOverrides(
											{
												avM34QCdd: {
													background: {
														alt: "",
														fit: "fill",
														pixelHeight: 1776,
														pixelWidth: 1296,
														sizes: `max(max(${componentViewport?.width || "100vw"}, 1px) - 24px, 1px)`,
														...toResponsiveImage(Hp5TV0EJT2),
													},
												},
												NWAjxHYDL: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 325) -
																		0 -
																		420) /
																		2) +
																20 +
																0,
														),
														pixelHeight: 1776,
														pixelWidth: 1296,
														sizes: `max((max(${componentViewport?.width || "100vw"}, 1px) - 40px) / 2.716 - 10px, 1px)`,
														...toResponsiveImage(Hp5TV0EJT2),
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<ComponentViewportProvider
										height={380}
										width={`min(max((max(${componentViewport?.width || "100vw"}, 1px) - 56px) / 2.716 - 10px, 1px), 324px)`}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 436) - 0 - 436) / 2) +
											28 +
											0
										}
										{...addPropertyOverrides(
											{
												"avM34QCdd-pressed": {
													y: void 0,
												},
												avM34QCdd: {
													height: 200,
													width: `calc(max(${componentViewport?.width || "100vw"}, 1px) - 24px)`,
													y: void 0,
												},
												NWAjxHYDL: {
													width: `max((max(${componentViewport?.width || "100vw"}, 1px) - 40px) / 2.716 - 10px, 1px)`,
													y:
														(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 325) - 0 - 420) /
																2) +
														20 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1x3fggg-container"}
											layoutDependency={layoutDependency}
											layoutId={"nCu6Fxm0X-container"}
											nodeId={"nCu6Fxm0X"}
											rendersWithMotion={true}
											scopeId={"B6STIL4OB"}
										>
											<RevealOverlayCaseStudyImageWithVariantAppearEffect
												__framer__animateOnce={true}
												__framer__obscuredVariantId={"qpwAhlJZm"}
												__framer__threshold={0.5}
												__framer__variantAppearEffectEnabled={true}
												__framer__visibleVariantId={"ZKMbXQYPw"}
												height={"100%"}
												id={"nCu6Fxm0X"}
												layoutId={"nCu6Fxm0X"}
												style={{
													height: "100%",
													width: "100%",
												}}
												tu3vRje3v={XiSILjU_N2}
												variant={"qpwAhlJZm"}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-65xmp.framer-1e1xotk, .framer-65xmp .framer-1e1xotk { display: block; }",
	".framer-65xmp.framer-cfg330 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: 936px; }",
	".framer-65xmp .framer-jzjwbx { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 28px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-65xmp .framer-ps7uzi { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: auto; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 20px 40px 20px 0px; position: relative; width: 63%; }",
	".framer-65xmp .framer-1vjd27a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 488px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-65xmp .framer-utmw43 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-65xmp .framer-lg596a, .framer-65xmp .framer-kh731f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 6px 16px 6px 16px; position: relative; width: min-content; }",
	".framer-65xmp .framer-mntxjh, .framer-65xmp .framer-mj9knu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-65xmp .framer-s3svm2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-65xmp .framer-ojqf01-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-65xmp .framer-xaqtgw { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 324px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-65xmp .framer-1dwb00q { aspect-ratio: 0.8526315789473684 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 380px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-65xmp .framer-1x3fggg-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-65xmp.framer-v-uuvr0z.framer-cfg330 { width: 618px; }",
	".framer-65xmp.framer-v-uuvr0z .framer-jzjwbx { padding: 20px; }",
	".framer-65xmp.framer-v-uuvr0z .framer-ps7uzi { padding: 16px 20px 16px 0px; }",
	".framer-65xmp.framer-v-uuvr0z .framer-xaqtgw, .framer-65xmp.framer-v-uuvr0z.hover .framer-xaqtgw, .framer-65xmp.framer-v-1k8kvqk.pressed .framer-xaqtgw { max-width: unset; }",
	".framer-65xmp.framer-v-uuvr0z .framer-1dwb00q { height: var(--framer-aspect-ratio-supported, 249px); }",
	".framer-65xmp.framer-v-1k8kvqk.framer-cfg330 { width: 310px; }",
	".framer-65xmp.framer-v-1k8kvqk .framer-jzjwbx { flex-direction: column; gap: 10px; justify-content: flex-start; padding: 12px; }",
	".framer-65xmp.framer-v-1k8kvqk .framer-ps7uzi { align-self: unset; gap: 40px; height: min-content; justify-content: center; order: 1; padding: 20px 40px 0px 0px; width: 100%; }",
	".framer-65xmp.framer-v-1k8kvqk .framer-utmw43 { flex-wrap: wrap; width: 100%; }",
	".framer-65xmp.framer-v-1k8kvqk .framer-xaqtgw { flex: none; max-width: unset; order: 0; width: 100%; }",
	".framer-65xmp.framer-v-1k8kvqk .framer-1dwb00q { aspect-ratio: 1.43 / 1; height: var(--framer-aspect-ratio-supported, 140px); }",
	".framer-65xmp.framer-v-uuvr0z.hover .framer-1dwb00q { height: var(--framer-aspect-ratio-supported, 250px); }",
	".framer-65xmp.framer-v-1k8kvqk.pressed .framer-ps7uzi { align-self: unset; }",
	...css,
	...css2,
	'.framer-65xmp[data-border="true"]::after, .framer-65xmp [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerB6STIL4OB = withCSS(Component, css3, "framer-65xmp");
var stdin_default3 = FramerB6STIL4OB;
FramerB6STIL4OB.displayName = "Case Study Card (Large)";
FramerB6STIL4OB.defaultProps = {
	height: 436,
	width: 936,
};
addPropertyControls(FramerB6STIL4OB, {
	variant: {
		options: ["fTqfa6zMT", "NWAjxHYDL", "avM34QCdd"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	At4Pr3rJk: {
		defaultValue: "2025",
		displayTextArea: false,
		title: "Year",
		type: ControlType.String,
	},
	xaGbPDv6W: {
		defaultValue: "Branding",
		displayTextArea: false,
		title: "Project Type",
		type: ControlType.String,
	},
	Os6cY3CKf: {
		defaultValue:
			"Crafting Orris\xE9: An Immersive Study in Fragrance Identity",
		displayTextArea: true,
		title: "Title",
		type: ControlType.String,
	},
	Hp5TV0EJT: {
		__defaultAssetReference:
			"data:framer/asset-reference,BYrxPxIvmunBK4mrRB4kWpT1pUs.png?originalFilename=Case+study+image+1.png&width=1296&height=1776",
		title: "Card Image",
		type: ControlType.ResponsiveImage,
	},
	XiSILjU_N: {
		defaultValue:
			'var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)) /* {"name":"Primary"} */',
		title: "BG Fill",
		type: ControlType.Color,
	},
	wprkFfBdg: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerB6STIL4OB,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonSecondaryLargeFonts,
		...RevealOverlayCaseStudyImageFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:case-study-card-large
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "avM34QCdd",
	md: "NWAjxHYDL",
	xl: "fTqfa6zMT",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CaseStudyCardLargeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var case_study_card_large_default = ComponentWithRoot;
export { case_study_card_large_default as default };
