// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default3 } from "./chunks/chunk-JSN6H32P.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-QFNO7QTN.js";
import { stdin_default } from "./chunks/chunk-D4ZDA44Q.js";
import { className, css, fonts } from "./chunks/chunk-3XNB3BOA.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:contact
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/djFfey9NU0XeSzCiQ4ia/x53oCHLxOHSeZoeZyaEh/oJ0HkbenH.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormContainer,
	FormPlainTextInput,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SectionTagFonts = getFonts(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var Image1WithFX = withFX(Image1);
var RichTextWithFX = withFX(RichText);
var NavLinksContactFonts = getFonts(stdin_default);
var SubmitButtonFonts = getFonts(stdin_default3);
var FormContainerWithFX = withFX(FormContainer);
var cycleOrder = ["IC9vStfAx", "ldA1GT6NY", "N5rZnwRwx"];
var serializationHash = "framer-B7zQF";
var variantClassNames = {
	IC9vStfAx: "framer-v-n69e4q",
	ldA1GT6NY: "framer-v-1qoexp",
	N5rZnwRwx: "framer-v-wb7gmj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var transition2 = {
	bounce: 0,
	delay: 0,
	duration: 1,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition3 = {
	bounce: 0,
	delay: 0.1,
	duration: 1,
	type: "spring",
};
var transition4 = {
	bounce: 0,
	delay: 0.2,
	duration: 1,
	type: "spring",
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
		default:
			return currentVariant;
	}
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "IC9vStfAx",
	Phone: "N5rZnwRwx",
	Tablet: "ldA1GT6NY",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	image,
	mail,
	mailLink,
	number,
	numberLink,
	text,
	width,
	...props
}) => {
	return {
		...props,
		LyebUAnXZ: image ??
			props.LyebUAnXZ ?? {
				pixelHeight: 1536,
				pixelWidth: 1024,
				src: "https://framerusercontent.com/images/jHcjBzfQIkxbEFOKSFoaxMP908I.png?width=1024&height=1536",
				srcSet:
					"https://framerusercontent.com/images/jHcjBzfQIkxbEFOKSFoaxMP908I.png?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/jHcjBzfQIkxbEFOKSFoaxMP908I.png?width=1024&height=1536 1024w",
			},
		s1W_Zr6Qz: number ?? props.s1W_Zr6Qz ?? "+849 88 67 97 65",
		T8wjmfFFv: mail ?? props.T8wjmfFFv ?? "leondesigner221@gmail.com",
		UevP3H2qk: mailLink ?? props.UevP3H2qk,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "IC9vStfAx",
		yQr_nvvaX: numberLink ?? props.yQr_nvvaX,
		zZjVo4iDN:
			text ??
			props.zZjVo4iDN ??
			"You bring the vision. I'll bring the pixels. Let's talk",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		LyebUAnXZ: LyebUAnXZ2,
		zZjVo4iDN: zZjVo4iDN2,
		s1W_Zr6Qz: s1W_Zr6Qz2,
		yQr_nvvaX: yQr_nvvaX2,
		T8wjmfFFv: T8wjmfFFv2,
		UevP3H2qk: UevP3H2qk2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IC9vStfAx",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-n69e4q",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"IC9vStfAx"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								ldA1GT6NY: {
									"data-framer-name": "Tablet",
								},
								N5rZnwRwx: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1x8vtl8"}
							data-framer-name={"Left Content"}
							layoutDependency={layoutDependency}
							layoutId={"L8adD0nVT"}
						>
							<motion.div
								className={"framer-1oi0i0c"}
								data-framer-name={"Tag & Image"}
								layoutDependency={layoutDependency}
								layoutId={"oYOuC2obf"}
							>
								<ComponentViewportProvider
									height={24}
									y={(componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 0}
									{...addPropertyOverrides(
										{
											N5rZnwRwx: {
												y: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1sviugp-container"}
										layoutDependency={layoutDependency}
										layoutId={"lpc8GkJar-container"}
										nodeId={"lpc8GkJar"}
										rendersWithMotion={true}
										scopeId={"oJ0HkbenH"}
									>
										{_jsx(stdin_default2, {
											Epkyl0OCB: "CONTACT",
											height: "100%",
											id: "lpc8GkJar",
											layoutId: "lpc8GkJar",
											variant: matchVariant("U2MqHHQZu"),
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
								<motion.div
									className={"framer-12ki6j0"}
									data-framer-name={"Image & Text"}
									layoutDependency={layoutDependency}
									layoutId={"m_fZHfSwu"}
								>
									<Image1WithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										as={"figure"}
										background={{
											alt: "Stylized blue-toned illustration of a bearded man in profile wearing glasses and a collared shirt.",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 48 + 8.5,
											),
											pixelHeight: 1536,
											pixelWidth: 1024,
											sizes: "96px",
											...toResponsiveImage(LyebUAnXZ2),
										}}
										className={"framer-1lxchd1"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"jUSSZtq_X"}
										style={{
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
										}}
										{...addPropertyOverrides(
											{
												ldA1GT6NY: {
													background: {
														alt: "Stylized blue-toned illustration of a bearded man in profile wearing glasses and a collared shirt.",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																0 +
																0 +
																0 +
																48 +
																0 +
																0,
														),
														pixelHeight: 1536,
														pixelWidth: 1024,
														sizes: "96px",
														...toResponsiveImage(LyebUAnXZ2),
													},
												},
												N5rZnwRwx: {
													background: {
														alt: "Stylized blue-toned illustration of a bearded man in profile wearing glasses and a collared shirt.",
														fit: "fill",
														pixelHeight: 1536,
														pixelWidth: 1024,
														sizes: "96px",
														...toResponsiveImage(LyebUAnXZ2),
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<RichTextWithFX
										__framer__animate={{
											transition: transition3,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__fromCanvasComponent={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-c8bn0a"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"moWhm6o0x"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={zZjVo4iDN2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-17e0ml2"}
												data-styles-preset={"Iwq8LBfrK"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
												}}
											>
												{
													"Reach out to start a conversation, share a vision, or create something impactful."
												}
											</motion.p>
										</React.Fragment>
									</RichTextWithFX>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-d63g7v"}
								data-framer-name={"Contact Info"}
								layoutDependency={layoutDependency}
								layoutId={"WVksSIft2"}
							>
								<ComponentViewportProvider
									height={26}
									y={(componentViewport?.y || 0) + 0 + 0 + 212 + 0 + 0}
									{...addPropertyOverrides(
										{
											ldA1GT6NY: {
												y: (componentViewport?.y || 0) + 0 + 0 + 335 + 0 + 0,
											},
											N5rZnwRwx: {
												y: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1k6dn0c-container"}
										layoutDependency={layoutDependency}
										layoutId={"V3akLsFSj-container"}
										nodeId={"V3akLsFSj"}
										rendersWithMotion={true}
										scopeId={"oJ0HkbenH"}
									>
										{_jsx(stdin_default, {
											e3NNhro77: true,
											EbaUaYhj2: s1W_Zr6Qz2,
											height: "100%",
											id: "V3akLsFSj",
											layoutId: "V3akLsFSj",
											qoQvdWCH7: yQr_nvvaX2,
											variant: matchVariant("CXV1UK0vX"),
											width: "100%",
											yDL3MWkA8: false,
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={26}
									y={(componentViewport?.y || 0) + 0 + 0 + 212 + 0 + 42}
									{...addPropertyOverrides(
										{
											ldA1GT6NY: {
												y: (componentViewport?.y || 0) + 0 + 0 + 335 + 0 + 42,
											},
											N5rZnwRwx: {
												y: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1v9sfgt-container"}
										layoutDependency={layoutDependency}
										layoutId={"sRDagyce_-container"}
										nodeId={"sRDagyce_"}
										rendersWithMotion={true}
										scopeId={"oJ0HkbenH"}
									>
										{_jsx(stdin_default, {
											e3NNhro77: false,
											EbaUaYhj2: T8wjmfFFv2,
											height: "100%",
											id: "sRDagyce_",
											layoutId: "sRDagyce_",
											qoQvdWCH7: UevP3H2qk2,
											variant: matchVariant("CXV1UK0vX"),
											width: "100%",
											yDL3MWkA8: true,
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
						<FormContainerWithFX
							__framer__animate={{
								transition: transition4,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							action={
								"https://api.framer.com/forms/v1/forms/d4ffc5bb-a3ac-47b0-b608-10a724972d65/submit"
							}
							className={"framer-10h2nu4"}
							layoutDependency={layoutDependency}
							layoutId={"zTBQWLjMD"}
							nodeId={"zTBQWLjMD"}
						>
							{(formState) => (
								<_Fragment>
									<motion.div
										className={"framer-1sx7h1w"}
										data-framer-name={"Label Wrapper"}
										layoutDependency={layoutDependency}
										layoutId={"Hd3yzEWQP"}
									>
										<motion.label
											className={"framer-eoeze8"}
											layoutDependency={layoutDependency}
											layoutId={"ul4_KmYpA"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-wkm3i9"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"x6_OpmwKF"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-17e0ml2"}
														data-styles-preset={"Iwq8LBfrK"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
														}}
													>
														{"Name"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<FormPlainTextInput
												className={"framer-imppdj"}
												inputName={"Name"}
												layoutDependency={layoutDependency}
												layoutId={"TBRdnV913"}
												placeholder={"Who am I talking to?"}
												required={true}
												style={{
													"--framer-input-border-bottom-width": "1px",
													"--framer-input-border-color":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
													"--framer-input-border-left-width": "0px",
													"--framer-input-border-right-width": "0px",
													"--framer-input-border-style": "solid",
													"--framer-input-border-top-width": "0px",
													"--framer-input-font-color":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
													"--framer-input-icon-color": "rgb(153, 153, 153)",
													"--framer-input-placeholder-color":
														"rgb(153, 153, 153)",
												}}
												type={"text"}
											/>
										</motion.label>
										<motion.label
											className={"framer-xsy7li"}
											layoutDependency={layoutDependency}
											layoutId={"yDkRO1SbB"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-gpjhaj"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"wBodZpHoG"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-17e0ml2"}
														data-styles-preset={"Iwq8LBfrK"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
														}}
													>
														{"Email"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<FormPlainTextInput
												className={"framer-b9fdr1"}
												inputName={"Email"}
												layoutDependency={layoutDependency}
												layoutId={"dW5kQLd3b"}
												placeholder={"No spam, pinky swear"}
												required={true}
												style={{
													"--framer-input-border-bottom-width": "1px",
													"--framer-input-border-color":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
													"--framer-input-border-left-width": "0px",
													"--framer-input-border-right-width": "0px",
													"--framer-input-border-style": "solid",
													"--framer-input-border-top-width": "0px",
													"--framer-input-font-color":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
													"--framer-input-icon-color": "rgb(153, 153, 153)",
													"--framer-input-placeholder-color":
														"rgb(153, 153, 153)",
												}}
												type={"email"}
											/>
										</motion.label>
										<motion.label
											className={"framer-15lgla8"}
											layoutDependency={layoutDependency}
											layoutId={"iNwvigC9h"}
										>
											<FormPlainTextInput
												className={"framer-1bgu75g"}
												inputName={"Message"}
												layoutDependency={layoutDependency}
												layoutId={"luzoCI7zp"}
												placeholder={"What's on your mind?"}
												style={{
													"--framer-input-border-bottom-width": "1px",
													"--framer-input-border-color":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
													"--framer-input-border-left-width": "0px",
													"--framer-input-border-right-width": "0px",
													"--framer-input-border-style": "solid",
													"--framer-input-border-top-width": "0px",
													"--framer-input-font-color":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
													"--framer-input-icon-color": "rgb(153, 153, 153)",
													"--framer-input-placeholder-color":
														"rgb(153, 153, 153)",
												}}
												type={"textarea"}
											/>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-8mv6k0"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"eUd0p2xSo"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-17e0ml2"}
														data-styles-preset={"Iwq8LBfrK"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
														}}
													>
														{"Message"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.label>
									</motion.div>
									<ComponentViewportProvider height={42}>
										<SmartComponentScopedContainer
											className={"framer-1nlsa9u-container"}
											layoutDependency={layoutDependency}
											layoutId={"y8sYlcCHZ-container"}
											nodeId={"y8sYlcCHZ"}
											rendersWithMotion={true}
											scopeId={"oJ0HkbenH"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "y8sYlcCHZ",
												layoutId: "y8sYlcCHZ",
												type: "submit",
												variant: formVariants(
													formState,
													{
														error: "SiEI4tyL1",
														incomplete: "Aa9sLX6lt",
														pending: "fwMrWbG2Y",
														success: "tGCp_yPYG",
													},
													matchVariant("ppm_rCnuF"),
												),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</_Fragment>
							)}
						</FormContainerWithFX>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-B7zQF.framer-1pjhedy, .framer-B7zQF .framer-1pjhedy { display: block; }",
	".framer-B7zQF.framer-n69e4q { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 936px; }",
	".framer-B7zQF .framer-1x8vtl8 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: flex-start; max-width: 360px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-B7zQF .framer-1oi0i0c { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-B7zQF .framer-1sviugp-container, .framer-B7zQF .framer-1k6dn0c-container, .framer-B7zQF .framer-1v9sfgt-container, .framer-B7zQF .framer-1nlsa9u-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-B7zQF .framer-12ki6j0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-B7zQF .framer-1lxchd1 { flex: none; gap: 0px; height: 111px; overflow: hidden; position: relative; width: 96px; will-change: var(--framer-will-change-override, transform); }",
	".framer-B7zQF .framer-c8bn0a { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-B7zQF .framer-d63g7v { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-B7zQF .framer-10h2nu4 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 28px; height: min-content; justify-content: flex-start; max-width: 360px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-B7zQF .framer-1sx7h1w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-B7zQF .framer-eoeze8, .framer-B7zQF .framer-xsy7li, .framer-B7zQF .framer-15lgla8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-B7zQF .framer-wkm3i9, .framer-B7zQF .framer-gpjhaj, .framer-B7zQF .framer-8mv6k0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	'.framer-B7zQF .framer-imppdj, .framer-B7zQF .framer-b9fdr1 { --framer-input-focused-border-color: var(--token-1615e446-4914-429c-9d6b-de0d358636dc, #004aad); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "CoconatLocal"; --framer-input-font-letter-spacing: -0.04em; --framer-input-font-line-height: 160%; --framer-input-font-size: 16px; --framer-input-font-weight: 400; --framer-input-padding: 12px; --framer-input-wrapper-height: auto; flex: none; height: auto; position: relative; width: 100%; }',
	'.framer-B7zQF .framer-1bgu75g { --framer-input-focused-border-color: var(--token-1615e446-4914-429c-9d6b-de0d358636dc, #004aad); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "CoconatLocal"; --framer-input-font-letter-spacing: -0.04em; --framer-input-font-line-height: 160%; --framer-input-font-size: 16px; --framer-input-font-weight: 400; --framer-input-padding: 12px; --framer-input-wrapper-height: auto; --framer-textarea-resize: vertical; flex: none; height: auto; min-height: 100px; position: relative; width: 100%; }',
	".framer-B7zQF.framer-v-1qoexp.framer-n69e4q { width: 738px; }",
	".framer-B7zQF.framer-v-1qoexp .framer-12ki6j0, .framer-B7zQF.framer-v-wb7gmj .framer-12ki6j0 { align-content: flex-start; align-items: flex-start; flex-direction: column; }",
	".framer-B7zQF.framer-v-1qoexp .framer-c8bn0a, .framer-B7zQF.framer-v-wb7gmj .framer-c8bn0a { flex: none; width: 80%; }",
	".framer-B7zQF.framer-v-1qoexp .framer-1sx7h1w { gap: 48px; }",
	".framer-B7zQF.framer-v-wb7gmj.framer-n69e4q { flex-direction: column; gap: 20px; justify-content: flex-start; width: 350px; }",
	".framer-B7zQF.framer-v-wb7gmj .framer-1x8vtl8 { flex: none; gap: 32px; width: 100%; }",
	".framer-B7zQF.framer-v-wb7gmj .framer-1oi0i0c, .framer-B7zQF.framer-v-wb7gmj .framer-1sx7h1w { gap: 16px; }",
	".framer-B7zQF.framer-v-wb7gmj .framer-d63g7v { gap: 12px; }",
	".framer-B7zQF.framer-v-wb7gmj .framer-10h2nu4 { flex: none; gap: 20px; width: 100%; }",
	...css,
];
var FrameroJ0HkbenH = withCSS(Component, css2, "framer-B7zQF");
var stdin_default4 = FrameroJ0HkbenH;
FrameroJ0HkbenH.displayName = "Contact";
FrameroJ0HkbenH.defaultProps = {
	height: 458,
	width: 936,
};
addPropertyControls(FrameroJ0HkbenH, {
	variant: {
		options: ["IC9vStfAx", "ldA1GT6NY", "N5rZnwRwx"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	LyebUAnXZ: {
		__defaultAssetReference:
			"data:framer/asset-reference,jHcjBzfQIkxbEFOKSFoaxMP908I.png?originalFilename=leon+tilted+left.png&width=1024&height=1536",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	zZjVo4iDN: {
		defaultValue: "You bring the vision. I'll bring the pixels. Let's talk",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
	onzZjVo4iDNChange: {
		changes: "zZjVo4iDN",
		type: ControlType.ChangeHandler,
	},
	s1W_Zr6Qz: {
		defaultValue: "+849 88 67 97 65",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	ons1W_Zr6QzChange: {
		changes: "s1W_Zr6Qz",
		type: ControlType.ChangeHandler,
	},
	yQr_nvvaX: {
		title: "Number Link",
		type: ControlType.Link,
	},
	T8wjmfFFv: {
		defaultValue: "leondesigner221@gmail.com",
		displayTextArea: false,
		title: "Mail",
		type: ControlType.String,
	},
	onT8wjmfFFvChange: {
		changes: "T8wjmfFFv",
		type: ControlType.ChangeHandler,
	},
	UevP3H2qk: {
		title: "Mail Link",
		type: ControlType.Link,
	},
});
addFonts(
	FrameroJ0HkbenH,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "CoconatLocal",
					source: "builtIn",
					style: "normal",
					uiFamilyName: "CoconatLocal",
					url: "/fonts/Coconat-Regular.woff2",
					weight: "400",
				},
			],
		},
		...SectionTagFonts,
		...NavLinksContactFonts,
		...SubmitButtonFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FrameroJ0HkbenH.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default, {}, context),
			forwardLoader(stdin_default3, {}, context),
		]);
	},
};

// virtual:contact
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "N5rZnwRwx",
	md: "ldA1GT6NY",
	xl: "IC9vStfAx",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ContactFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var contact_default = ComponentWithRoot;
export { contact_default as default };
