// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-KBFRVL6M.js";
import { className, css, fonts } from "./chunks/chunk-3XNB3BOA.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/urbet971rALaEzT7JEO9/ABv09XfAk7d6RsN6QvtN/pSTD1aeEX.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/hYe56xz6rpBu5DTc8xAx/9JlGXJmOgCGJbyEnySj9/eiBciD27r.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Instrument Serif-regular",
	"GF;Instrument Serif-italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Instrument Serif",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/instrumentserif/v5/jizBRFtNs2ka5fXjeivQ4LroWlx-2zcZj1bIkNo.woff2",
				weight: "400",
			},
			{
				family: "Instrument Serif",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/instrumentserif/v5/jizHRFtNs2ka5fXjeivQ4LroWlx-6zATjnTNgNq55w.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	'.framer-EakUC .framer-styles-preset-1e3szrq:not(.rich-text-wrapper), .framer-EakUC .framer-styles-preset-1e3szrq.rich-text-wrapper h5 { --framer-font-family: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-family-italic: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.04em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-1615e446-4914-429c-9d6b-de0d358636dc, #004aad); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-EakUC .framer-styles-preset-1e3szrq:not(.rich-text-wrapper), .framer-EakUC .framer-styles-preset-1e3szrq.rich-text-wrapper h5 { --framer-font-family: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-family-italic: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.04em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-1615e446-4914-429c-9d6b-de0d358636dc, #004aad); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-EakUC .framer-styles-preset-1e3szrq:not(.rich-text-wrapper), .framer-EakUC .framer-styles-preset-1e3szrq.rich-text-wrapper h5 { --framer-font-family: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-family-italic: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.04em; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-1615e446-4914-429c-9d6b-de0d358636dc, #004aad); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-EakUC";

// /:https://framerusercontent.com/modules/rIaXlJdkHSlFSWjpROuu/Mv8t4B9IBRL4HvvP5l3m/tC0Gc8bdb.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css3 = [
	'.framer-Txesp .framer-styles-preset-hhrw3s:not(.rich-text-wrapper), .framer-Txesp .framer-styles-preset-hhrw3s.rich-text-wrapper a { --framer-link-current-text-decoration: underline; --framer-link-current-text-decoration-color: var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, #f6f4f0) /* {"name":"Secondary"} */; --framer-link-current-text-decoration-thickness: 1px; --framer-link-hover-text-color: var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, #f6f4f0); --framer-link-hover-text-decoration: underline; --framer-link-hover-text-decoration-color: var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, #f6f4f0) /* {"name":"Secondary"} */; --framer-link-hover-text-decoration-thickness: 1px; --framer-link-text-color: var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, #f6f4f0); }',
];
var className3 = "framer-Txesp";

// /:https://framerusercontent.com/modules/urbet971rALaEzT7JEO9/ABv09XfAk7d6RsN6QvtN/pSTD1aeEX.js
var NavLinksSocialFonts = getFonts(stdin_default);
var cycleOrder = ["rROgsCBED", "NWflAUyGJ", "m0780Hnqn"];
var serializationHash = "framer-JVs6r";
var variantClassNames = {
	m0780Hnqn: "framer-v-199yyn5",
	NWflAUyGJ: "framer-v-1ut0izv",
	rROgsCBED: "framer-v-17em8t2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "rROgsCBED",
	Phone: "m0780Hnqn",
	Tablet: "NWflAUyGJ",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "rROgsCBED",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "rROgsCBED",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["NWflAUyGJ", "m0780Hnqn"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17em8t2",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"rROgsCBED"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								m0780Hnqn: {
									"data-framer-name": "Phone",
								},
								NWflAUyGJ: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-ixot1w"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"gPapo75uU"}
						>
							<motion.div
								className={"framer-s2rleo"}
								data-framer-name={"All Links"}
								layoutDependency={layoutDependency}
								layoutId={"kSmZBWBhw"}
							>
								<motion.div
									className={"framer-n4wam"}
									data-framer-name={"Links Content"}
									layoutDependency={layoutDependency}
									layoutId={"zVWryDUPq"}
								>
									<motion.div
										className={"framer-ykezs9"}
										data-border={true}
										data-framer-name={"Logo & Social Links Wrap"}
										layoutDependency={layoutDependency}
										layoutId={"Hlz_4avlF"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-a8b7161f-e6d5-4443-9830-30523ca077cb, rgba(255, 255, 255, 0.2))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											borderBottomLeftRadius: 16,
											borderBottomRightRadius: 16,
											borderTopLeftRadius: 16,
											borderTopRightRadius: 16,
										}}
									>
										<motion.div
											className={"framer-15lhzra"}
											data-framer-name={"Logo & Social Links"}
											layoutDependency={layoutDependency}
											layoutId={"jNPQk3UFg"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-15d55zp"}
												fonts={[]}
												layoutDependency={layoutDependency}
												layoutId={"rXmL5MKGH"}
												style={{
													"--extracted-2gxw0f": "rgb(255, 255, 255)",
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector": "Qkk7Q29jb25hdC9SZWd1bGFyL3Yw",
															"--framer-font-family": '"CoconatLocal", sans-serif',
															"--framer-font-size": "48px",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"Leon "}
													</motion.p>
													<motion.p
														dir={"auto"}
														style={{
															"--font-selector": "Qkk7Q29jb25hdC9SZWd1bGFyL3Yw",
															"--framer-font-family": '"CoconatLocal", sans-serif',
															"--framer-font-size": "48px",
															"--framer-text-color":
																"var(--extracted-2gxw0f, rgb(255, 255, 255))",
														}}
													>
														{"Nguyen"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<motion.div
												className={"framer-1hq8x53"}
												data-framer-name={"Social Links"}
												layoutDependency={layoutDependency}
												layoutId={"uzwIF_RSF"}
											>
												<motion.div
													className={"framer-1tedzb9"}
													data-framer-name={"Left"}
													layoutDependency={layoutDependency}
													layoutId={"QqxJnmLu9"}
												>
													<ComponentViewportProvider
														height={38}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															104 +
															0 +
															0 +
															0 +
															0 +
															48 +
															0 +
															167.8 +
															0 +
															0 +
															0
														}
														{...addPropertyOverrides(
															{
																m0780Hnqn: {
																	y: void 0,
																},
																NWflAUyGJ: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		0 +
																		80 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		40 +
																		0 +
																		131.2 +
																		0 +
																		0 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-1rnj4u0-container"}
															layoutDependency={layoutDependency}
															layoutId={"qkBITuXIu-container"}
															nodeId={"qkBITuXIu"}
															rendersWithMotion={true}
															scopeId={"pSTD1aeEX"}
														>
															{_jsx(stdin_default, {
																height: "100%",
																id: "qkBITuXIu",
																layoutId: "qkBITuXIu",
																tcXlSOnTp: "Linkedin",
																ubX46UqjJ: "https://www.linkedin.com/",
																width: "100%",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												</motion.div>
												{isDisplayed() && (
													<motion.div
														className={"framer-1l5hs0a"}
														data-framer-name={"Right"}
														layoutDependency={layoutDependency}
														layoutId={"i33HIOg2p"}
													/>
												)}
											</motion.div>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1mxrm4j"}
												data-framer-name={
													"Copyright \xA9James Parker, All right reserved"
												}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"ufsXOE_pt"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
													"--framer-paragraph-spacing": "0px",
												}}
												variants={{
													m0780Hnqn: {
														"--extracted-2gxw0f":
															"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
													},
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														m0780Hnqn: {
															children: (
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-17e0ml2"}
																		data-styles-preset={"Iwq8LBfrK"}
																		dir={"auto"}
																		style={{
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
																		}}
																	>
																		{
																			"Design can be automated, but great design "
																		}
																	</motion.p>
																	<motion.p
																		className={"framer-styles-preset-17e0ml2"}
																		data-styles-preset={"Iwq8LBfrK"}
																		dir={"auto"}
																		style={{
																			"--framer-text-color":
																				"var(--extracted-2gxw0f, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
																		}}
																	>
																		{"cannot"}
																	</motion.p>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-17e0ml2"}
														data-styles-preset={"Iwq8LBfrK"}
														dir={"auto"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
														}}
													>
														{"Design can be automated, but great design cannot"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-8h5xq6"}
										data-border={true}
										data-framer-name={"Nav Links Wrap"}
										layoutDependency={layoutDependency}
										layoutId={"bysPjei_h"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-a8b7161f-e6d5-4443-9830-30523ca077cb, rgba(255, 255, 255, 0.2))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											borderBottomLeftRadius: 16,
											borderBottomRightRadius: 16,
											borderTopLeftRadius: 16,
											borderTopRightRadius: 16,
										}}
									>
										<motion.div
											className={"framer-1flwflz"}
											data-framer-name={"Nav Links"}
											layoutDependency={layoutDependency}
											layoutId={"GlU1VaEd8"}
										>
											<motion.div
												className={"framer-1dro8bm"}
												data-framer-name={"Main Page"}
												layoutDependency={layoutDependency}
												layoutId={"XX05RqOGS"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1viovvk"}
													data-framer-name={"Title"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"owxhCBmki"}
													style={{
														"--extracted-1lwpl3i":
															"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.h5
															className={"framer-styles-preset-1e3szrq"}
															data-styles-preset={"eiBciD27r"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
															}}
														>
															{"Main Page"}
														</motion.h5>
													</React.Fragment>
												</RichText>
												<motion.ul
													className={"framer-n6wpa1"}
													data-framer-name={"Links"}
													layoutDependency={layoutDependency}
													layoutId={"SyQc8v50r"}
												>
													<RichText
														__fromCanvasComponent={true}
														as={"li"}
														className={"framer-pwzny4"}
														data-framer-name={"Home"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"mRSHDYkgy"}
														style={{
															"--extracted-r6o4lv":
																"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-17e0ml2"}
																data-styles-preset={"Iwq8LBfrK"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
																}}
															>
																<Link
																	href={{
																		webPageId: "augiA20Il",
																	}}
																	motionChild={true}
																	nodeId={"mRSHDYkgy"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"pSTD1aeEX"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-hhrw3s"}
																		data-styles-preset={"tC0Gc8bdb"}
																	>
																		{"Home"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
													<RichText
														__fromCanvasComponent={true}
														as={"li"}
														className={"framer-oiypf4"}
														data-framer-name={"About"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"xaahCLNsi"}
														style={{
															"--extracted-r6o4lv":
																"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-17e0ml2"}
																data-styles-preset={"Iwq8LBfrK"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
																}}
															>
																<Link
																	href={{
																		webPageId: "q5CeafqEX",
																	}}
																	motionChild={true}
																	nodeId={"xaahCLNsi"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"pSTD1aeEX"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-hhrw3s"}
																		data-styles-preset={"tC0Gc8bdb"}
																	>
																		{"About"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
													<RichText
														__fromCanvasComponent={true}
														as={"li"}
														className={"framer-fotyeu"}
														data-framer-name={"Case Study"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"UcSBhEavi"}
														style={{
															"--extracted-r6o4lv":
																"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-17e0ml2"}
																data-styles-preset={"Iwq8LBfrK"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
																}}
															>
																<Link
																	href={{
																		webPageId: "pKlD29wmQ",
																	}}
																	motionChild={true}
																	nodeId={"UcSBhEavi"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"pSTD1aeEX"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-hhrw3s"}
																		data-styles-preset={"tC0Gc8bdb"}
																	>
																		{"Case Study"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
													<RichText
														__fromCanvasComponent={true}
														as={"li"}
														className={"framer-gfbvzh"}
														data-framer-name={"Blog"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"rwKoUfXBc"}
														style={{
															"--extracted-r6o4lv":
																"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-17e0ml2"}
																data-styles-preset={"Iwq8LBfrK"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
																}}
															>
																<Link
																	href={{
																		webPageId: "Y6B68u4Dk",
																	}}
																	motionChild={true}
																	nodeId={"rwKoUfXBc"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"pSTD1aeEX"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-hhrw3s"}
																		data-styles-preset={"tC0Gc8bdb"}
																	>
																		{"Blog"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
													<RichText
														__fromCanvasComponent={true}
														as={"li"}
														className={"framer-1duhqpe"}
														data-framer-name={"Contact"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"jNMBqcTCg"}
														style={{
															"--extracted-r6o4lv":
																"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-17e0ml2"}
																data-styles-preset={"Iwq8LBfrK"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
																}}
															>
																<Link
																	href={{
																		webPageId: "S7_h2jQo9",
																	}}
																	motionChild={true}
																	nodeId={"jNMBqcTCg"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"pSTD1aeEX"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-hhrw3s"}
																		data-styles-preset={"tC0Gc8bdb"}
																	>
																		{"Contact"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
												</motion.ul>
											</motion.div>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JVs6r.framer-q2gkto, .framer-JVs6r .framer-q2gkto { display: block; }",
	".framer-JVs6r.framer-17em8t2 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
	".framer-JVs6r .framer-ixot1w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: var(--overflow-clip-fallback, clip); padding: 104px 36px 40px 36px; position: relative; width: 100%; }",
	".framer-JVs6r .framer-s2rleo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-JVs6r .framer-n4wam { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-JVs6r .framer-ykezs9 { align-content: center; align-items: center; aspect-ratio: 1.4526315789473685 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 380px); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 48px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-JVs6r .framer-15lhzra { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
	".framer-JVs6r .framer-15d55zp, .framer-JVs6r .framer-1mxrm4j, .framer-JVs6r .framer-1viovvk, .framer-JVs6r .framer-pwzny4, .framer-JVs6r .framer-oiypf4, .framer-JVs6r .framer-fotyeu, .framer-JVs6r .framer-gfbvzh, .framer-JVs6r .framer-1duhqpe { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-JVs6r .framer-1hq8x53 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-JVs6r .framer-1tedzb9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-JVs6r .framer-1rnj4u0-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-JVs6r .framer-1l5hs0a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: flex-start; min-height: 37px; min-width: 83px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-JVs6r .framer-8h5xq6 { align-content: flex-start; align-items: flex-start; aspect-ratio: 1.4526315789473685 / 1; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 380px); justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 48px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-JVs6r .framer-1flwflz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-JVs6r .framer-1dro8bm { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-JVs6r .framer-n6wpa1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; list-style: none; margin: 0px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-JVs6r.framer-v-1ut0izv.framer-17em8t2 { width: 810px; }",
	".framer-JVs6r.framer-v-1ut0izv .framer-ixot1w { padding: 80px 36px 40px 36px; }",
	".framer-JVs6r.framer-v-1ut0izv .framer-n4wam { flex-direction: column; }",
	".framer-JVs6r.framer-v-1ut0izv .framer-ykezs9, .framer-JVs6r.framer-v-1ut0izv .framer-8h5xq6 { aspect-ratio: unset; flex: none; height: min-content; padding: 40px; width: 100%; }",
	".framer-JVs6r.framer-v-1ut0izv .framer-15lhzra, .framer-JVs6r.framer-v-199yyn5 .framer-15lhzra { gap: 16px; height: min-content; justify-content: center; }",
	".framer-JVs6r.framer-v-1ut0izv .framer-1hq8x53 { gap: 60px; }",
	".framer-JVs6r.framer-v-1ut0izv .framer-1dro8bm, .framer-JVs6r.framer-v-1ut0izv .framer-1viovvk { order: 0; }",
	".framer-JVs6r.framer-v-1ut0izv .framer-n6wpa1 { order: 1; }",
	".framer-JVs6r.framer-v-199yyn5.framer-17em8t2 { width: 390px; }",
	".framer-JVs6r.framer-v-199yyn5 .framer-ixot1w { padding: 40px 20px 20px 20px; }",
	".framer-JVs6r.framer-v-199yyn5 .framer-s2rleo, .framer-JVs6r.framer-v-199yyn5 .framer-1dro8bm { gap: 20px; }",
	".framer-JVs6r.framer-v-199yyn5 .framer-n4wam { flex-direction: column; gap: 16px; }",
	".framer-JVs6r.framer-v-199yyn5 .framer-ykezs9, .framer-JVs6r.framer-v-199yyn5 .framer-8h5xq6 { aspect-ratio: unset; flex: none; height: min-content; padding: 24px; width: 100%; }",
	".framer-JVs6r.framer-v-199yyn5 .framer-1hq8x53 { align-content: flex-start; align-items: flex-start; flex-wrap: wrap; gap: 26px 26px; }",
	".framer-JVs6r.framer-v-199yyn5 .framer-1tedzb9 { gap: 26px; }",
	".framer-JVs6r.framer-v-199yyn5 .framer-1flwflz { flex-wrap: wrap; gap: 40px 80px; justify-content: flex-start; }",
	...css,
	...css2,
	...css3,
	'.framer-JVs6r[data-border="true"]::after, .framer-JVs6r [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerpSTD1aeEX = withCSS(Component, css4, "framer-JVs6r");
var stdin_default2 = FramerpSTD1aeEX;
FramerpSTD1aeEX.displayName = "Footer";
FramerpSTD1aeEX.defaultProps = {
	height: 524,
	width: 1200,
};
addPropertyControls(FramerpSTD1aeEX, {
	variant: {
		options: ["rROgsCBED", "NWflAUyGJ", "m0780Hnqn"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerpSTD1aeEX,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "CoconatLocal",
					source: "builtIn",
					style: "normal",
					uiFamilyName: "CoconatLocal",
					url: "/fonts/Coconat-Regular.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...NavLinksSocialFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerpSTD1aeEX.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "m0780Hnqn",
	md: "NWflAUyGJ",
	xl: "rROgsCBED",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
