// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Features - Desktop' | 'Location - Deaktop' | 'Time- Desktop' | 'Availability - Desktop' | 'Blank - Desktop' | 'Features - Tablet' | 'Location - Tablet' | 'Time- Tablet' | 'Availability - Tablet' | 'Blank - Tablet' // Variant
 * starLeftTopVisible?: boolean // Star left top Visible
 * ong6sUgTSXFChange?: undefined // ong6sUgTSXFChange
 * starRightTopVisible?: boolean // Star Right top Visible
 * onpKfZ5d16KCHange?: undefined // onpKfZ5d16KCHange
 * starLeftBottomVisible?: boolean // Star left bottom Visible
 * onoqZxZyQk3Change?: undefined // onoqZxZyQk3Change
 * starRightBottomVisible?: boolean // Star Right bottom Visible
 * onrDvuQE1CmChange?: undefined // onrDvuQE1CmChange
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-W3JQDOIA.js";
import { TimeDisplay } from "./chunks/chunk-LDJGA6JN.js";
import { className, css, fonts } from "./chunks/chunk-3XNB3BOA.js";
import { stdin_default } from "./chunks/chunk-2K4JLNZ7.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:hero-card-bottom
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8CJM5xxh4BaLgfHIGvb2/hI2R0LXK84F2eSbA4PlO/KuJvgIMup.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Image1WithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(Image1),
);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var StarHeroFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var TimeDisplayFonts = getFonts(TimeDisplay);
var AvailableStatusAnimatedFonts = getFonts(stdin_default2);
var cycleOrder = [
	"kTapeUbls",
	"FTnS9Q99N",
	"zzyRktD2N",
	"NxJH7NVHT",
	"hLwhdLFKY",
	"z2TYIw6kq",
	"XzoslglRt",
	"K_oofrFNU",
	"w0C71yf2w",
	"rPtwz1zSq",
];
var serializationHash = "framer-s3Gde";
var variantClassNames = {
	FTnS9Q99N: "framer-v-1wwgwgh",
	hLwhdLFKY: "framer-v-1jdgsp1",
	K_oofrFNU: "framer-v-i7iagd",
	kTapeUbls: "framer-v-1g4kfe3",
	NxJH7NVHT: "framer-v-1mv6kn1",
	rPtwz1zSq: "framer-v-y23s6o",
	w0C71yf2w: "framer-v-13frkii",
	XzoslglRt: "framer-v-e47qih",
	z2TYIw6kq: "framer-v-1ag6irp",
	zzyRktD2N: "framer-v-bkfiih",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	bounce: 0,
	delay: 0.5,
	duration: 1,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	bounce: 0,
	delay: 0.4,
	duration: 1,
	type: "spring",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation3 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: -160,
	y: 0,
};
var transition4 = {
	bounce: 0,
	delay: 0.6,
	duration: 1,
	type: "spring",
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var transition5 = {
	bounce: 0,
	delay: 0.7,
	duration: 1,
	type: "spring",
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 0,
};
var animation6 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Availability - Desktop": "NxJH7NVHT",
	"Availability - Tablet": "w0C71yf2w",
	"Blank - Desktop": "hLwhdLFKY",
	"Blank - Tablet": "rPtwz1zSq",
	"Features - Desktop": "kTapeUbls",
	"Features - Tablet": "z2TYIw6kq",
	"Location - Deaktop": "FTnS9Q99N",
	"Location - Tablet": "XzoslglRt",
	"Time- Desktop": "zzyRktD2N",
	"Time- Tablet": "K_oofrFNU",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	starLeftBottomVisible,
	starLeftTopVisible,
	starRightBottomVisible,
	starRightTopVisible,
	width,
	...props
}) => {
	return {
		...props,
		g6sUgTSXf: starLeftTopVisible ?? props.g6sUgTSXf ?? true,
		oqZxZyQk3: starLeftBottomVisible ?? props.oqZxZyQk3 ?? true,
		pKfZ5d16K: starRightTopVisible ?? props.pKfZ5d16K ?? true,
		rDvuQE1Cm: starRightBottomVisible ?? props.rDvuQE1Cm ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "kTapeUbls",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		g6sUgTSXf: g6sUgTSXf2,
		pKfZ5d16K: pKfZ5d16K2,
		oqZxZyQk3: oqZxZyQk32,
		rDvuQE1Cm: rDvuQE1Cm2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "kTapeUbls",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			["NxJH7NVHT", "hLwhdLFKY", "w0C71yf2w", "rPtwz1zSq"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (
			[
				"FTnS9Q99N",
				"zzyRktD2N",
				"NxJH7NVHT",
				"hLwhdLFKY",
				"XzoslglRt",
				"K_oofrFNU",
				"w0C71yf2w",
				"rPtwz1zSq",
			].includes(baseVariant)
		)
			return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (
			["FTnS9Q99N", "zzyRktD2N", "XzoslglRt", "K_oofrFNU"].includes(baseVariant)
		)
			return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (["NxJH7NVHT", "w0C71yf2w"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1g4kfe3",
							className2,
							classNames,
						)}
						data-framer-name={"Features - Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"kTapeUbls"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								FTnS9Q99N: {
									"data-framer-name": "Location - Deaktop",
								},
								hLwhdLFKY: {
									"data-framer-name": "Blank - Desktop",
								},
								K_oofrFNU: {
									"data-framer-name": "Time- Tablet",
								},
								NxJH7NVHT: {
									"data-framer-name": "Availability - Desktop",
								},
								rPtwz1zSq: {
									"data-framer-name": "Blank - Tablet",
								},
								w0C71yf2w: {
									"data-framer-name": "Availability - Tablet",
								},
								XzoslglRt: {
									"data-framer-name": "Location - Tablet",
								},
								z2TYIw6kq: {
									"data-framer-name": "Features - Tablet",
								},
								zzyRktD2N: {
									"data-framer-name": "Time- Desktop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-igcdy0"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"JcxA_FNur"}
							style={{
								backgroundColor:
									"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
							}}
						>
							<motion.div
								className={"framer-1s0u8e0"}
								data-border={true}
								data-framer-name={"Border + BG Grain"}
								layoutDependency={layoutDependency}
								layoutId={"Z9IoCRk2q"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-d4a89c75-b136-459b-b396-44f6e2b83800, rgb(221, 227, 233))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							>
								{isDisplayed() && (
									<Image1WithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										as={"figure"}
										background={{
											alt: "BG Grain",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 204) - 0 - 204) /
															2) +
													0 +
													0,
											),
											pixelHeight: 1632,
											pixelWidth: 1504,
											sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
											src: "https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?width=1504&height=1632",
											srcSet:
												"https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?scale-down-to=1024&width=1504&height=1632 943w,https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?width=1504&height=1632 1504w",
										}}
										className={"framer-ehzlkq"}
										data-framer-appear-id={"ehzlkq"}
										data-framer-name={"GRAIN"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"qwK6LPi8P"}
										optimized={true}
										style={{
											borderBottomLeftRadius: 16,
											borderBottomRightRadius: 16,
											borderTopLeftRadius: 16,
											borderTopRightRadius: 16,
										}}
										{...addPropertyOverrides(
											{
												K_oofrFNU: {
													background: {
														alt: "BG Grain",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 201) -
																		0 -
																		204) /
																		2) +
																0 +
																0,
														),
														pixelHeight: 1632,
														pixelWidth: 1504,
														sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
														src: "https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?width=1504&height=1632",
														srcSet:
															"https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?scale-down-to=1024&width=1504&height=1632 943w,https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?width=1504&height=1632 1504w",
													},
												},
												XzoslglRt: {
													background: {
														alt: "BG Grain",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 201) -
																		0 -
																		204) /
																		2) +
																0 +
																0,
														),
														pixelHeight: 1632,
														pixelWidth: 1504,
														sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
														src: "https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?width=1504&height=1632",
														srcSet:
															"https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?scale-down-to=1024&width=1504&height=1632 943w,https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?width=1504&height=1632 1504w",
													},
												},
												z2TYIw6kq: {
													background: {
														alt: "BG Grain",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 201) -
																		0 -
																		204) /
																		2) +
																0 +
																0,
														),
														pixelHeight: 1632,
														pixelWidth: 1504,
														sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
														src: "https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?width=1504&height=1632",
														srcSet:
															"https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?scale-down-to=1024&width=1504&height=1632 943w,https://framerusercontent.com/images/edmaCY5StOhlr7v3E63KrJ7GZg.png?width=1504&height=1632 1504w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								)}
							</motion.div>
							{isDisplayed1() && (
								<motion.div
									className={"framer-6p5sh0"}
									data-framer-name={"Features"}
									layoutDependency={layoutDependency}
									layoutId={"gS1_bKqMB"}
								>
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation2}
										className={"framer-1ccw8r8"}
										data-framer-appear-id={"1ccw8r8"}
										data-framer-name={"F1"}
										initial={animation3}
										layoutDependency={layoutDependency}
										layoutId={"eMkadxhbV"}
										optimized={true}
									>
										<SVG
											className={"framer-i4j6ty"}
											data-framer-name={"Line 5"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"XeT7IK5p9"}
											opacity={1}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 10 3"><path d="M 1 1.5 L 9 1.5" fill="transparent" stroke="var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)) /* {&quot;name&quot;:&quot;Primary&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
											}
											svgContentId={11149069003}
											withExternalLayout={true}
										/>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-ed66rr"}
											data-framer-name={"UI/UX Design"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"FyYlfXGgp"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-17e0ml2"}
													data-styles-preset={"Iwq8LBfrK"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
													}}
												>
													{"UI/UX Design"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</MotionDivWithFXWithOptimizedAppearEffect>
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-15oxpm7"}
										data-framer-appear-id={"15oxpm7"}
										data-framer-name={"F2"}
										initial={animation3}
										layoutDependency={layoutDependency}
										layoutId={"i1zdXWLFi"}
										optimized={true}
									>
										<SVG
											className={"framer-yn9vfd"}
											data-framer-name={"Line 5"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"UYPiR1FeY"}
											opacity={1}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 10 3"><path d="M 1 1.5 L 9 1.5" fill="transparent" stroke="var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)) /* {&quot;name&quot;:&quot;Primary&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
											}
											svgContentId={11149069003}
											withExternalLayout={true}
										/>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1q06rod"}
											data-framer-name={"Illustration"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"vO03csKWl"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-17e0ml2"}
													data-styles-preset={"Iwq8LBfrK"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
													}}
												>
													{"Graphic Design"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</MotionDivWithFXWithOptimizedAppearEffect>
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation4}
										className={"framer-1s46sqf"}
										data-framer-appear-id={"1s46sqf"}
										data-framer-name={"F3"}
										initial={animation3}
										layoutDependency={layoutDependency}
										layoutId={"wbkEvrwon"}
										optimized={true}
									>
										<SVG
											className={"framer-p31u5y"}
											data-framer-name={"Line 5"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"GsfaKtzcE"}
											opacity={1}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 10 3"><path d="M 1 1.5 L 9 1.5" fill="transparent" stroke="var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)) /* {&quot;name&quot;:&quot;Primary&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
											}
											svgContentId={11149069003}
											withExternalLayout={true}
										/>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1pcnoea"}
											data-framer-name={"Copy Writing"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"bnlEdnWTw"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-17e0ml2"}
													data-styles-preset={"Iwq8LBfrK"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
													}}
												>
													{"AI-Powered UI/UX"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</MotionDivWithFXWithOptimizedAppearEffect>
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation5}
										className={"framer-1fubdoh"}
										data-framer-appear-id={"1fubdoh"}
										data-framer-name={"F4"}
										initial={animation3}
										layoutDependency={layoutDependency}
										layoutId={"sM6mA5INK"}
										optimized={true}
									>
										<SVG
											className={"framer-1tiwah0"}
											data-framer-name={"Line 5"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"dnyvzxAxy"}
											opacity={1}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 10 3"><path d="M 1 1.5 L 9 1.5" fill="transparent" stroke="var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)) /* {&quot;name&quot;:&quot;Primary&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
											}
											svgContentId={11149069003}
											withExternalLayout={true}
										/>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-c97kjw"}
											data-framer-name={"Branding Design"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"VO6c51fHS"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-17e0ml2"}
													data-styles-preset={"Iwq8LBfrK"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
													}}
												>
													{"Branding Design"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</MotionDivWithFXWithOptimizedAppearEffect>
								</motion.div>
							)}
							{g6sUgTSXf2 !== false && (
								<ComponentViewportProvider
									height={12}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 204) - 0 - 204) / 2) +
										-6
									}
									{...addPropertyOverrides(
										{
											K_oofrFNU: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
											rPtwz1zSq: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
											w0C71yf2w: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
											XzoslglRt: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
											z2TYIw6kq: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-4xdjyq-container"}
										data-framer-appear-id={"4xdjyq"}
										data-framer-name={"Star - Left top"}
										initial={animation6}
										layoutDependency={layoutDependency}
										layoutId={"yE_hMTwjj-container"}
										name={"Star - Left top"}
										nodeId={"yE_hMTwjj"}
										optimized={true}
										rendersWithMotion={true}
										scopeId={"KuJvgIMup"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "yE_hMTwjj",
											layoutId: "yE_hMTwjj",
											name: "Star - Left top",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
								</ComponentViewportProvider>
							)}
							{pKfZ5d16K2 !== false && (
								<ComponentViewportProvider
									height={12}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 204) - 0 - 204) / 2) +
										-6
									}
									{...addPropertyOverrides(
										{
											K_oofrFNU: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
											rPtwz1zSq: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
											w0C71yf2w: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
											XzoslglRt: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
											z2TYIw6kq: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													-6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-1ff4n16-container"}
										data-framer-appear-id={"1ff4n16"}
										data-framer-name={"Star - Right top"}
										initial={animation6}
										layoutDependency={layoutDependency}
										layoutId={"nB3TgWmVF-container"}
										name={"Star - Right top"}
										nodeId={"nB3TgWmVF"}
										optimized={true}
										rendersWithMotion={true}
										scopeId={"KuJvgIMup"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "nB3TgWmVF",
											layoutId: "nB3TgWmVF",
											name: "Star - Right top",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
								</ComponentViewportProvider>
							)}
							{oqZxZyQk32 !== false && (
								<ComponentViewportProvider
									height={12}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 204) - 0 - 204) / 2) +
										204 -
										6
									}
									{...addPropertyOverrides(
										{
											K_oofrFNU: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
											rPtwz1zSq: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
											w0C71yf2w: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
											XzoslglRt: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
											z2TYIw6kq: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-1i045g5-container"}
										data-framer-appear-id={"1i045g5"}
										data-framer-name={"Star - Left bottom"}
										initial={animation6}
										layoutDependency={layoutDependency}
										layoutId={"osN7wsHBz-container"}
										name={"Star - Left bottom"}
										nodeId={"osN7wsHBz"}
										optimized={true}
										rendersWithMotion={true}
										scopeId={"KuJvgIMup"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "osN7wsHBz",
											layoutId: "osN7wsHBz",
											name: "Star - Left bottom",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
								</ComponentViewportProvider>
							)}
							{rDvuQE1Cm2 !== false && (
								<ComponentViewportProvider
									height={12}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 204) - 0 - 204) / 2) +
										204 -
										6
									}
									{...addPropertyOverrides(
										{
											K_oofrFNU: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
											rPtwz1zSq: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
											w0C71yf2w: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
											XzoslglRt: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
											z2TYIw6kq: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													204 -
													6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-8yzq54-container"}
										data-framer-appear-id={"8yzq54"}
										data-framer-name={"Star - Right bottom"}
										initial={animation6}
										layoutDependency={layoutDependency}
										layoutId={"f9yQKr8nO-container"}
										name={"Star - Right bottom"}
										nodeId={"f9yQKr8nO"}
										optimized={true}
										rendersWithMotion={true}
										scopeId={"KuJvgIMup"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "f9yQKr8nO",
											layoutId: "f9yQKr8nO",
											name: "Star - Right bottom",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
								</ComponentViewportProvider>
							)}
							{isDisplayed2() && (
								<motion.div
									className={"framer-1g0v0do"}
									data-framer-name={"Time Component"}
									layoutDependency={layoutDependency}
									layoutId={"Woxb530Yz"}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-yecoki-container"}
											data-code-component-plugin-id={"84d4c1"}
											isAuthoredByUser={true}
											layoutDependency={layoutDependency}
											layoutId={"E1ElcK00U-container"}
											nodeId={"E1ElcK00U"}
											rendersWithMotion={true}
											scopeId={"KuJvgIMup"}
										>
											<TimeDisplay
												backgroundColor={
													"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))"
												}
												dateFormat={"short"}
												enableBackground={false}
												gap={8}
												height={"100%"}
												id={"E1ElcK00U"}
												layoutId={"E1ElcK00U"}
												locationColor={
													"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))"
												}
												locationFont={{
													fontFamily: '"IBM Plex Mono", monospace',
													fontSize: "16px",
													fontStyle: "normal",
													fontWeight: 400,
													letterSpacing: "-0.04em",
													lineHeight: "160%",
												}}
												padding={0}
												showDate={false}
												showLocation={true}
												showSeconds={true}
												showTime={true}
												textColor={
													"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))"
												}
												timeFont={{
													fontFamily: '"IBM Plex Mono", monospace',
													fontSize: "16px",
													fontStyle: "normal",
													fontWeight: 400,
													letterSpacing: "-0.04em",
													lineHeight: "160%",
												}}
												timeFormat={"12"}
												width={"100%"}
												{...addPropertyOverrides(
													{
														FTnS9Q99N: {
															locationFont: {
																fontFamily: '"Coconat", sans-serif',
																fontSize: "16px",
																fontStyle: "normal",
																fontWeight: 400,
																letterSpacing: "-0.04em",
																lineHeight: "160%",
															},
															showTime: false,
															timeFont: {
																fontFamily: '"Coconat", sans-serif',
																fontSize: "16px",
																fontStyle: "normal",
																fontWeight: 400,
																letterSpacing: "-0.04em",
																lineHeight: "160%",
															},
														},
														K_oofrFNU: {
															showLocation: false,
															showSeconds: false,
															timeFont: {
																fontFamily: '"Coconat", sans-serif',
																fontSize: "16px",
																fontStyle: "normal",
																fontWeight: 400,
																letterSpacing: "-0.04em",
																lineHeight: "160%",
															},
														},
														XzoslglRt: {
															locationFont: {
																fontFamily: '"Coconat", sans-serif',
																fontSize: "16px",
																fontStyle: "normal",
																fontWeight: 400,
																letterSpacing: "-0.04em",
																lineHeight: "160%",
															},
															showTime: false,
															timeFont: {
																fontFamily: '"Coconat", sans-serif',
																fontSize: "16px",
																fontStyle: "normal",
																fontWeight: 400,
																letterSpacing: "-0.04em",
																lineHeight: "160%",
															},
														},
														zzyRktD2N: {
															showLocation: false,
															showSeconds: false,
															timeFont: {
																fontFamily: '"Coconat", sans-serif',
																fontSize: "16px",
																fontStyle: "normal",
																fontWeight: 400,
																letterSpacing: "-0.04em",
																lineHeight: "160%",
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							)}
							{isDisplayed3() && (
								<ComponentViewportProvider
									{...addPropertyOverrides(
										{
											NxJH7NVHT: {
												height: 26,
												width: `calc(max(${componentViewport?.width || "100vw"}, 1px) - 32px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 204) - 0 - 204) /
															2) +
													16 +
													146,
											},
											w0C71yf2w: {
												height: 26,
												width: `calc(max(${componentViewport?.width || "100vw"}, 1px) - 24px)`,
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 201) - 0 - 204) /
															2) +
													12 +
													154,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-16mdygg-container"}
										layoutDependency={layoutDependency}
										layoutId={"a395vD68I-container"}
										nodeId={"a395vD68I"}
										rendersWithMotion={true}
										scopeId={"KuJvgIMup"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "a395vD68I",
											layoutId: "a395vD68I",
											variant: matchVariant("fBm8gquG1"),
											width: "100%",
											...addPropertyOverrides(
												{
													NxJH7NVHT: {
														style: {
															width: "100%",
														},
													},
													w0C71yf2w: {
														style: {
															width: "100%",
														},
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-s3Gde.framer-pdgbgg, .framer-s3Gde .framer-pdgbgg { display: block; }",
	".framer-s3Gde.framer-1g4kfe3 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 188px; }",
	".framer-s3Gde .framer-igcdy0 { align-content: center; align-items: center; aspect-ratio: 0.9215686274509803 / 1; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 204px); justify-content: center; overflow: visible; padding: 16px; position: relative; width: 1px; }",
	".framer-s3Gde .framer-1s0u8e0 { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: hidden; padding: 0px; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); }",
	".framer-s3Gde .framer-ehzlkq { flex: none; height: 100%; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 0; }",
	".framer-s3Gde .framer-6p5sh0 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-s3Gde .framer-1ccw8r8, .framer-s3Gde .framer-15oxpm7, .framer-s3Gde .framer-1s46sqf, .framer-s3Gde .framer-1fubdoh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-s3Gde .framer-i4j6ty, .framer-s3Gde .framer-yn9vfd, .framer-s3Gde .framer-p31u5y, .framer-s3Gde .framer-1tiwah0 { flex: none; height: 3px; position: relative; width: 10px; }",
	".framer-s3Gde .framer-ed66rr, .framer-s3Gde .framer-1q06rod, .framer-s3Gde .framer-1pcnoea, .framer-s3Gde .framer-c97kjw { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-s3Gde .framer-4xdjyq-container { flex: none; height: auto; left: -6px; position: absolute; top: -6px; width: auto; z-index: 1; }",
	".framer-s3Gde .framer-1ff4n16-container { flex: none; height: auto; position: absolute; right: -6px; top: -6px; width: auto; z-index: 1; }",
	".framer-s3Gde .framer-1i045g5-container { bottom: -6px; flex: none; height: auto; left: -6px; position: absolute; width: auto; z-index: 1; }",
	".framer-s3Gde .framer-8yzq54-container { bottom: -6px; flex: none; height: auto; position: absolute; right: -6px; width: auto; z-index: 1; }",
	".framer-s3Gde .framer-1g0v0do { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-s3Gde .framer-yecoki-container, .framer-s3Gde .framer-16mdygg-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-s3Gde.framer-v-1wwgwgh .framer-igcdy0, .framer-s3Gde.framer-v-1wwgwgh .framer-1g0v0do, .framer-s3Gde.framer-v-bkfiih .framer-igcdy0, .framer-s3Gde.framer-v-1mv6kn1 .framer-igcdy0, .framer-s3Gde.framer-v-e47qih .framer-1g0v0do { justify-content: flex-end; }",
	".framer-s3Gde.framer-v-bkfiih .framer-1g0v0do, .framer-s3Gde.framer-v-i7iagd .framer-1g0v0do { justify-content: flex-start; }",
	".framer-s3Gde.framer-v-1mv6kn1 .framer-16mdygg-container, .framer-s3Gde.framer-v-13frkii .framer-16mdygg-container { width: 100%; }",
	".framer-s3Gde.framer-v-1ag6irp.framer-1g4kfe3, .framer-s3Gde.framer-v-e47qih.framer-1g4kfe3, .framer-s3Gde.framer-v-i7iagd.framer-1g4kfe3, .framer-s3Gde.framer-v-13frkii.framer-1g4kfe3, .framer-s3Gde.framer-v-y23s6o.framer-1g4kfe3 { width: 185px; }",
	".framer-s3Gde.framer-v-1ag6irp .framer-igcdy0, .framer-s3Gde.framer-v-y23s6o .framer-igcdy0 { height: var(--framer-aspect-ratio-supported, 201px); padding: 12px; }",
	".framer-s3Gde.framer-v-1ag6irp .framer-1ccw8r8, .framer-s3Gde.framer-v-1ag6irp .framer-15oxpm7, .framer-s3Gde.framer-v-1ag6irp .framer-1s46sqf, .framer-s3Gde.framer-v-1ag6irp .framer-1fubdoh { gap: 4px; }",
	".framer-s3Gde.framer-v-e47qih .framer-igcdy0, .framer-s3Gde.framer-v-i7iagd .framer-igcdy0, .framer-s3Gde.framer-v-13frkii .framer-igcdy0 { height: var(--framer-aspect-ratio-supported, 201px); justify-content: flex-end; padding: 12px; }",
	...css,
	'.framer-s3Gde[data-border="true"]::after, .framer-s3Gde [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerKuJvgIMup = withCSS(Component, css2, "framer-s3Gde");
var stdin_default3 = FramerKuJvgIMup;
FramerKuJvgIMup.displayName = "Hero Card - Bottom";
FramerKuJvgIMup.defaultProps = {
	height: 204,
	width: 188,
};
addPropertyControls(FramerKuJvgIMup, {
	variant: {
		options: [
			"kTapeUbls",
			"FTnS9Q99N",
			"zzyRktD2N",
			"NxJH7NVHT",
			"hLwhdLFKY",
			"z2TYIw6kq",
			"XzoslglRt",
			"K_oofrFNU",
			"w0C71yf2w",
			"rPtwz1zSq",
		],
		optionTitles: [
			"Features - Desktop",
			"Location - Deaktop",
			"Time- Desktop",
			"Availability - Desktop",
			"Blank - Desktop",
			"Features - Tablet",
			"Location - Tablet",
			"Time- Tablet",
			"Availability - Tablet",
			"Blank - Tablet",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	g6sUgTSXf: {
		defaultValue: true,
		title: "Star left top Visible",
		type: ControlType.Boolean,
	},
	ong6sUgTSXfChange: {
		changes: "g6sUgTSXf",
		type: ControlType.ChangeHandler,
	},
	pKfZ5d16K: {
		defaultValue: true,
		title: "Star Right top Visible",
		type: ControlType.Boolean,
	},
	onpKfZ5d16KChange: {
		changes: "pKfZ5d16K",
		type: ControlType.ChangeHandler,
	},
	oqZxZyQk3: {
		defaultValue: true,
		title: "Star left bottom Visible",
		type: ControlType.Boolean,
	},
	onoqZxZyQk3Change: {
		changes: "oqZxZyQk3",
		type: ControlType.ChangeHandler,
	},
	rDvuQE1Cm: {
		defaultValue: true,
		title: "Star Right bottom Visible",
		type: ControlType.Boolean,
	},
	onrDvuQE1CmChange: {
		changes: "rDvuQE1Cm",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerKuJvgIMup,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "IBM Plex Mono",
					source: "google",
					style: "normal",
					uiFamilyName: "IBM Plex Mono",
					url: "https://fonts.gstatic.com/s/ibmplexmono/v20/-F63fjptAgt5VM-kVkqdyU8n5i0g1l9kn-s.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Coconat",
					source: "builtIn",
					style: "normal",
					uiFamilyName: "Coconat",
					url: "https://framerusercontent.com/assets/ajqZQvqHcHYfzV6VYjZCsDHG6kM.woff2",
					weight: "400",
				},
			],
		},
		...StarHeroFonts,
		...TimeDisplayFonts,
		...AvailableStatusAnimatedFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerKuJvgIMup.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default, {}, context),
			forwardLoader(stdin_default2, {}, context),
		]);
	},
};

// virtual:hero-card-bottom
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "K_oofrFNU",
	xl: "FTnS9Q99N",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroCardBottomFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var hero_card_bottom_default = ComponentWithRoot;
export { hero_card_bottom_default as default };
