// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:menu-burger
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/nCuoLV683mtRdm6nldB6/4YbdTkSZgyAEJCdnLF6C/UU1uu7wHQ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["Lx_tDDg6v", "JdDCLD_DZ"];
var serializationHash = "framer-fOJLS";
var variantClassNames = {
	JdDCLD_DZ: "framer-v-euf25n",
	Lx_tDDg6v: "framer-v-1f7vwk3",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Cross: "JdDCLD_DZ",
	Menu: "Lx_tDDg6v",
};
var getProps = ({ height, id, menu, width, ...props }) => {
	return {
		...props,
		KBPVAkIBd: menu ?? props.KBPVAkIBd,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Lx_tDDg6v",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, KBPVAkIBd, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Lx_tDDg6v",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap930gtu = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (KBPVAkIBd) {
			const res = await KBPVAkIBd(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1f7vwk3",
							className,
							classNames,
						)}
						data-framer-name={"Menu"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"Lx_tDDg6v"}
						onTap={onTap930gtu}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								JdDCLD_DZ: {
									"data-framer-name": "Cross",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-fvs5cr"}
							data-framer-name={"Helper"}
							layoutDependency={layoutDependency}
							layoutId={"yPeAIQ1uA"}
						>
							<motion.div
								className={"framer-si6j0a"}
								data-framer-name={"Bottom"}
								layoutDependency={layoutDependency}
								layoutId={"WHqT19oFb"}
								style={{
									backgroundColor:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
									rotate: 0,
								}}
								variants={{
									JdDCLD_DZ: {
										rotate: -45,
									},
								}}
							/>
							<motion.div
								className={"framer-1p1xzrh"}
								data-framer-name={"Mid"}
								layoutDependency={layoutDependency}
								layoutId={"kUIDXdgNp"}
								style={{
									backgroundColor:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							/>
							<motion.div
								className={"framer-jhe9c9"}
								data-framer-name={"Top"}
								layoutDependency={layoutDependency}
								layoutId={"pWEcfF4gf"}
								style={{
									backgroundColor:
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
									rotate: 0,
								}}
								variants={{
									JdDCLD_DZ: {
										rotate: 45,
									},
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-fOJLS.framer-13xjb5m, .framer-fOJLS .framer-13xjb5m { display: block; }",
	".framer-fOJLS.framer-1f7vwk3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-fOJLS .framer-fvs5cr { flex: none; height: 28px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 28px; }",
	".framer-fOJLS .framer-si6j0a { bottom: 5px; flex: none; height: 2px; left: calc(50.00000000000002% - 22px / 2); overflow: visible; position: absolute; width: 22px; }",
	".framer-fOJLS .framer-1p1xzrh { flex: none; height: 2px; left: calc(50.00000000000002% - 22px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 22px; }",
	".framer-fOJLS .framer-jhe9c9 { flex: none; height: 2px; left: calc(50.00000000000002% - 22px / 2); overflow: visible; position: absolute; top: 5px; width: 22px; }",
	".framer-fOJLS.framer-v-euf25n .framer-si6j0a { bottom: 13px; }",
	".framer-fOJLS.framer-v-euf25n .framer-1p1xzrh { left: calc(50.00000000000002% - 1px / 2); width: 1px; }",
	".framer-fOJLS.framer-v-euf25n .framer-jhe9c9 { top: calc(50.00000000000002% - 2px / 2); }",
];
var FramerUU1uu7wHQ = withCSS(Component, css, "framer-fOJLS");
var stdin_default = FramerUU1uu7wHQ;
FramerUU1uu7wHQ.displayName = "Menu Burger";
FramerUU1uu7wHQ.defaultProps = {
	height: 28,
	width: 28,
};
addPropertyControls(FramerUU1uu7wHQ, {
	variant: {
		options: ["Lx_tDDg6v", "JdDCLD_DZ"],
		optionTitles: ["Menu", "Cross"],
		title: "Variant",
		type: ControlType.Enum,
	},
	KBPVAkIBd: {
		title: "Menu",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerUU1uu7wHQ,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:menu-burger
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MenuBurgerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var menu_burger_default = ComponentWithRoot;
export { menu_burger_default as default };
