// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop + Tablet' | 'Phone - Open 1 (No Effect Helper)' | 'Phone - Open 1' | 'Phone - Open 2' | 'Phone - Open 3' | 'Phone - Open 4' // Variant
}} Props

 */
import { AvoidLayoutJumping } from "./chunks/chunk-C2KZ2SUB.js";
import { stdin_default } from "./chunks/chunk-KHYXCJV7.js";
import "./chunks/chunk-K27265EC.js";
import "./chunks/chunk-3XNB3BOA.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:service-cards
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tiVjF4RBo4QaVaCu8TzQ/p3gVXzxWz71hUjmLTCaQ/TDnl0cBgd.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var ServiceCardFonts = getFonts(stdin_default);
var cycleOrder = [
	"BqPVTW8Ho",
	"bzO26Eqr7",
	"gf6fdSsg_",
	"JDDsMtkXi",
	"ZQDRtOZzz",
	"xqLXf3nRA",
];
var serializationHash = "framer-S0ATB";
var variantClassNames = {
	BqPVTW8Ho: "framer-v-1lx5tqg",
	bzO26Eqr7: "framer-v-qvrsm2",
	gf6fdSsg_: "framer-v-1o10r5e",
	JDDsMtkXi: "framer-v-1mpuzfy",
	xqLXf3nRA: "framer-v-1bmsg8",
	ZQDRtOZzz: "framer-v-swk99e",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var transition2 = {
	duration: 0,
	type: "tween",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Desktop + Tablet": "BqPVTW8Ho",
	"Phone - Open 1 (No Effect Helper)": "bzO26Eqr7",
	"Phone - Open 1": "gf6fdSsg_",
	"Phone - Open 2": "JDDsMtkXi",
	"Phone - Open 3": "ZQDRtOZzz",
	"Phone - Open 4": "xqLXf3nRA",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "BqPVTW8Ho",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "BqPVTW8Ho",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1l2mg4d = activeVariantCallback(async (...args) => {
		setVariant("gf6fdSsg_", true);
	});
	const bpNhItH39o0kuyq = activeVariantCallback(async (...args) => {
		setVariant("gf6fdSsg_");
	});
	const bpNhItH39t8y377 = activeVariantCallback(async (...args) => {
		setVariant("JDDsMtkXi");
	});
	const bpNhItH3911wlous = activeVariantCallback(async (...args) => {
		setVariant("ZQDRtOZzz");
	});
	const bpNhItH391g3tgh8 = activeVariantCallback(async (...args) => {
		setVariant("xqLXf3nRA");
	});
	useOnVariantChange(baseVariant, {
		bzO26Eqr7: onAppear1l2mg4d,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							bzO26Eqr7: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1lx5tqg",
							className,
							classNames,
						)}
						data-framer-name={"Desktop + Tablet"}
						layoutDependency={layoutDependency}
						layoutId={"BqPVTW8Ho"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								bzO26Eqr7: {
									"data-framer-name": "Phone - Open 1 (No Effect Helper)",
									"data-highlight": true,
								},
								gf6fdSsg_: {
									"data-framer-name": "Phone - Open 1",
								},
								JDDsMtkXi: {
									"data-framer-name": "Phone - Open 2",
								},
								xqLXf3nRA: {
									"data-framer-name": "Phone - Open 4",
								},
								ZQDRtOZzz: {
									"data-framer-name": "Phone - Open 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-ecmlg7-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"kbgAii7Bd-container"}
								nodeId={"kbgAii7Bd"}
								rendersWithMotion={true}
								scopeId={"TDnl0cBgd"}
							>
								<AvoidLayoutJumping
									direction={"vertical"}
									height={"100%"}
									id={"kbgAii7Bd"}
									layoutId={"kbgAii7Bd"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={96}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 384) - 0 - 384) / 2 + 0 + 0)
							}
							{...addPropertyOverrides(
								{
									bzO26Eqr7: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 320) - 0 - 384) / 2 +
												0 +
												0),
									},
									gf6fdSsg_: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												0 +
												0),
									},
									JDDsMtkXi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												0 +
												0),
									},
									xqLXf3nRA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												0 +
												0),
									},
									ZQDRtOZzz: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1vwez37-container"}
								layoutDependency={layoutDependency}
								layoutId={"x_1HEbSEH-container"}
								nodeId={"x_1HEbSEH"}
								rendersWithMotion={true}
								scopeId={"TDnl0cBgd"}
							>
								{_jsx(stdin_default, {
									gXiCOHBRU: "00-1",
									height: "100%",
									id: "x_1HEbSEH",
									layoutId: "x_1HEbSEH",
									MqojEsAL8: "0 \u2192 1 Product Design",
									SJ2ierF_S:
										"Crafting engaging websites that blend style with seamless usability.",
									SO7M6HTTY: addImageAlt(
										{
											pixelHeight: 768,
											pixelWidth: 1024,
											src: "https://framerusercontent.com/images/pW5PEW2mFcthRdUH1wbTRo7oc.webp?width=1024&height=768",
											srcSet:
												"https://framerusercontent.com/images/pW5PEW2mFcthRdUH1wbTRo7oc.webp?scale-down-to=512&width=1024&height=768 512w,https://framerusercontent.com/images/pW5PEW2mFcthRdUH1wbTRo7oc.webp?width=1024&height=768 1024w",
										},
										"Webpage promoting AI tool for generating short videos from text",
									),
									style: {
										width: "100%",
									},
									variant: matchVariant("ynna1GAie"),
									width: "100%",
									...addPropertyOverrides(
										{
											bzO26Eqr7: {
												variant: matchVariant("D9OnZHHAw"),
											},
											gf6fdSsg_: {
												variant: matchVariant("g8RTVSTzw"),
											},
											JDDsMtkXi: {
												bpNhItH39: bpNhItH39o0kuyq,
												variant: matchVariant("D9OnZHHAw"),
											},
											xqLXf3nRA: {
												bpNhItH39: bpNhItH39o0kuyq,
												variant: matchVariant("D9OnZHHAw"),
											},
											ZQDRtOZzz: {
												bpNhItH39: bpNhItH39o0kuyq,
												variant: matchVariant("D9OnZHHAw"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={96}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 384) - 0 - 384) / 2 + 96 + 0)
							}
							{...addPropertyOverrides(
								{
									bzO26Eqr7: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 320) - 0 - 384) / 2 +
												96 +
												0),
									},
									gf6fdSsg_: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												96 +
												0),
									},
									JDDsMtkXi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												96 +
												0),
									},
									xqLXf3nRA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												96 +
												0),
									},
									ZQDRtOZzz: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												96 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-g68asl-container"}
								layoutDependency={layoutDependency}
								layoutId={"sVxm3wbF6-container"}
								nodeId={"sVxm3wbF6"}
								rendersWithMotion={true}
								scopeId={"TDnl0cBgd"}
							>
								{_jsx(stdin_default, {
									gXiCOHBRU: "00-2",
									height: "100%",
									id: "sVxm3wbF6",
									layoutId: "sVxm3wbF6",
									MqojEsAL8: "AI Systems",
									SJ2ierF_S:
										"Creating intuitive app experiences that delight and empower users.",
									SO7M6HTTY: addImageAlt(
										{
											pixelHeight: 768,
											pixelWidth: 1024,
											src: "https://framerusercontent.com/images/PQHPYD2nzc5TJJq1eoPOQjbdPs.webp?width=1024&height=768",
											srcSet:
												"https://framerusercontent.com/images/PQHPYD2nzc5TJJq1eoPOQjbdPs.webp?scale-down-to=512&width=1024&height=768 512w,https://framerusercontent.com/images/PQHPYD2nzc5TJJq1eoPOQjbdPs.webp?width=1024&height=768 1024w",
										},
										"Habit tracker app UI showing progress chart and daily routines on mobile screen",
									),
									style: {
										width: "100%",
									},
									variant: matchVariant("ynna1GAie"),
									width: "100%",
									...addPropertyOverrides(
										{
											bzO26Eqr7: {
												bpNhItH39: void 0,
												variant: matchVariant("D9OnZHHAw"),
											},
											gf6fdSsg_: {
												bpNhItH39: bpNhItH39t8y377,
												variant: matchVariant("D9OnZHHAw"),
											},
											JDDsMtkXi: {
												variant: matchVariant("g8RTVSTzw"),
											},
											xqLXf3nRA: {
												bpNhItH39: bpNhItH39t8y377,
												variant: matchVariant("D9OnZHHAw"),
											},
											ZQDRtOZzz: {
												bpNhItH39: bpNhItH39t8y377,
												variant: matchVariant("D9OnZHHAw"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={96}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 384) - 0 - 384) / 2 + 192 + 0)
							}
							{...addPropertyOverrides(
								{
									bzO26Eqr7: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 320) - 0 - 384) / 2 +
												192 +
												0),
									},
									gf6fdSsg_: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												192 +
												0),
									},
									JDDsMtkXi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												192 +
												0),
									},
									xqLXf3nRA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												192 +
												0),
									},
									ZQDRtOZzz: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												192 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1tnah6e-container"}
								layoutDependency={layoutDependency}
								layoutId={"KVKHIMVNC-container"}
								nodeId={"KVKHIMVNC"}
								rendersWithMotion={true}
								scopeId={"TDnl0cBgd"}
							>
								{_jsx(stdin_default, {
									gXiCOHBRU: "00-3",
									height: "100%",
									id: "KVKHIMVNC",
									layoutId: "KVKHIMVNC",
									MqojEsAL8: "Web3 Products",
									SJ2ierF_S:
										"Designing identities where story meets timeless aesthetics.",
									SO7M6HTTY: addImageAlt(
										{
											pixelHeight: 916,
											pixelWidth: 940,
											src: "https://framerusercontent.com/images/8qD6J2rTeUdrPAmVaU53TH755U.png?width=940&height=916",
											srcSet:
												"https://framerusercontent.com/images/8qD6J2rTeUdrPAmVaU53TH755U.png?scale-down-to=512&width=940&height=916 512w,https://framerusercontent.com/images/8qD6J2rTeUdrPAmVaU53TH755U.png?width=940&height=916 940w",
										},
										"Blue pump bottle with silver dispenser and blank white label on a vibrant blue background",
									),
									style: {
										width: "100%",
									},
									variant: matchVariant("ynna1GAie"),
									width: "100%",
									...addPropertyOverrides(
										{
											bzO26Eqr7: {
												bpNhItH39: void 0,
												variant: matchVariant("D9OnZHHAw"),
											},
											gf6fdSsg_: {
												bpNhItH39: bpNhItH3911wlous,
												variant: matchVariant("D9OnZHHAw"),
											},
											JDDsMtkXi: {
												bpNhItH39: bpNhItH3911wlous,
												variant: matchVariant("D9OnZHHAw"),
											},
											xqLXf3nRA: {
												bpNhItH39: bpNhItH3911wlous,
												variant: matchVariant("D9OnZHHAw"),
											},
											ZQDRtOZzz: {
												variant: matchVariant("g8RTVSTzw"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={96}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 384) - 0 - 384) / 2 + 288 + 0)
							}
							{...addPropertyOverrides(
								{
									bzO26Eqr7: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 320) - 0 - 384) / 2 +
												288 +
												0),
									},
									gf6fdSsg_: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												288 +
												0),
									},
									JDDsMtkXi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												288 +
												0),
									},
									xqLXf3nRA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												288 +
												0),
									},
									ZQDRtOZzz: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 665) - 0 - 384) / 2 +
												288 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-v20tyb-container"}
								layoutDependency={layoutDependency}
								layoutId={"lLL_aMaEo-container"}
								nodeId={"lLL_aMaEo"}
								rendersWithMotion={true}
								scopeId={"TDnl0cBgd"}
							>
								{_jsx(stdin_default, {
									gXiCOHBRU: "00-4",
									height: "100%",
									id: "lLL_aMaEo",
									layoutId: "lLL_aMaEo",
									MqojEsAL8: "Rapid Prototyping",
									SJ2ierF_S:
										"Building robust digital solutions that perform and scale effortlessly.",
									SO7M6HTTY: addImageAlt(
										{
											pixelHeight: 3456,
											pixelWidth: 5184,
											src: "https://framerusercontent.com/images/DLDg5nZv9Yu5l30Tib9TNMOJhc.jpg?width=5184&height=3456",
											srcSet:
												"https://framerusercontent.com/images/DLDg5nZv9Yu5l30Tib9TNMOJhc.jpg?scale-down-to=512&width=5184&height=3456 512w,https://framerusercontent.com/images/DLDg5nZv9Yu5l30Tib9TNMOJhc.jpg?scale-down-to=1024&width=5184&height=3456 1024w,https://framerusercontent.com/images/DLDg5nZv9Yu5l30Tib9TNMOJhc.jpg?scale-down-to=2048&width=5184&height=3456 2048w,https://framerusercontent.com/images/DLDg5nZv9Yu5l30Tib9TNMOJhc.jpg?scale-down-to=4096&width=5184&height=3456 4096w,https://framerusercontent.com/images/DLDg5nZv9Yu5l30Tib9TNMOJhc.jpg?width=5184&height=3456 5184w",
										},
										"MacBook Pro showing HTML and CSS code in VS Code against a blue background",
									),
									style: {
										width: "100%",
									},
									variant: matchVariant("ynna1GAie"),
									width: "100%",
									...addPropertyOverrides(
										{
											bzO26Eqr7: {
												bpNhItH39: void 0,
												variant: matchVariant("D9OnZHHAw"),
											},
											gf6fdSsg_: {
												bpNhItH39: bpNhItH391g3tgh8,
												variant: matchVariant("D9OnZHHAw"),
											},
											JDDsMtkXi: {
												bpNhItH39: bpNhItH391g3tgh8,
												variant: matchVariant("D9OnZHHAw"),
											},
											xqLXf3nRA: {
												variant: matchVariant("g8RTVSTzw"),
											},
											ZQDRtOZzz: {
												bpNhItH39: bpNhItH391g3tgh8,
												variant: matchVariant("D9OnZHHAw"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-S0ATB.framer-bcem8q, .framer-S0ATB .framer-bcem8q { display: block; }",
	".framer-S0ATB.framer-1lx5tqg { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 546px; }",
	".framer-S0ATB .framer-ecmlg7-container { flex: none; height: auto; left: 0px; position: absolute; top: 0px; width: auto; z-index: 1; }",
	".framer-S0ATB .framer-1vwez37-container, .framer-S0ATB .framer-g68asl-container, .framer-S0ATB .framer-1tnah6e-container, .framer-S0ATB .framer-v20tyb-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-S0ATB.framer-v-qvrsm2.framer-1lx5tqg, .framer-S0ATB.framer-v-1o10r5e.framer-1lx5tqg, .framer-S0ATB.framer-v-1mpuzfy.framer-1lx5tqg, .framer-S0ATB.framer-v-swk99e.framer-1lx5tqg, .framer-S0ATB.framer-v-1bmsg8.framer-1lx5tqg { width: 350px; }",
];
var FramerTDnl0cBgd = withCSS(Component, css, "framer-S0ATB");
var stdin_default2 = FramerTDnl0cBgd;
FramerTDnl0cBgd.displayName = "Service Cards";
FramerTDnl0cBgd.defaultProps = {
	height: 384,
	width: 546,
};
addPropertyControls(FramerTDnl0cBgd, {
	variant: {
		options: [
			"BqPVTW8Ho",
			"bzO26Eqr7",
			"gf6fdSsg_",
			"JDDsMtkXi",
			"ZQDRtOZzz",
			"xqLXf3nRA",
		],
		optionTitles: [
			"Desktop + Tablet",
			"Phone - Open 1 (No Effect Helper)",
			"Phone - Open 1",
			"Phone - Open 2",
			"Phone - Open 3",
			"Phone - Open 4",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerTDnl0cBgd,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LayoutJumpPreventerFonts,
		...ServiceCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerTDnl0cBgd.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:service-cards
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "bzO26Eqr7",
	xl: "BqPVTW8Ho",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceCardsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var service_cards_default = ComponentWithRoot;
export { service_cards_default as default };
