// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop + Tablet' | 'Phone' // Variant
 * number?: string // Number
 * title?: string // Title
 * radius?: undefined // Radius
 * starLeftTop?: boolean // Star Left top
 * starLeftBottom?: boolean // Star Left bottom
 * starRightTop?: boolean // Star Right top
 * starRightBottom?: boolean // Star Right bottom
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UOQGEBQU.js";
import { className, css, fonts } from "./chunks/chunk-3XNB3BOA.js";
import { stdin_default } from "./chunks/chunk-2K4JLNZ7.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:statistics-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mksni67A1OJYKZeMGCfp/MBRVFVHy6ChUyz8NR5rV/vNoPOUtG5.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RichTextWithFX = withFX(RichText);
var StarHeroFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder = ["T4B4Qb96n", "jcZSVN2ZM"];
var serializationHash = "framer-UGwME";
var variantClassNames = {
	jcZSVN2ZM: "framer-v-1mchtog",
	T4B4Qb96n: "framer-v-f7dliy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var radiusForCorner = (value, cornerIndex) => {
	if (typeof value === "number" && Number.isFinite(value))
		return Math.max(0, value) + "px";
	if (typeof value !== "string" || typeof cornerIndex !== "number")
		return void 0;
	const segments = value.split(" ");
	return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 30,
	y: 0,
};
var transition2 = {
	bounce: 0.25,
	delay: 0.1,
	duration: 0.65,
	type: "spring",
};
var textEffect = {
	effect: animation,
	startDelay: 0.2,
	tokenization: "character",
	transition: transition2,
	trigger: "onInView",
	type: "appear",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var transition3 = {
	bounce: 0,
	delay: 0,
	duration: 1,
	type: "spring",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition4 = {
	bounce: 0,
	delay: 0.5,
	duration: 1,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop + Tablet": "T4B4Qb96n",
	Phone: "jcZSVN2ZM",
};
var getProps = ({
	height,
	id,
	number,
	radius,
	starLeftBottom,
	starLeftTop,
	starRightBottom,
	starRightTop,
	title,
	width,
	...props
}) => {
	return {
		...props,
		dlzgQhR5n: starLeftBottom ?? props.dlzgQhR5n,
		IaudNAPNv: number ?? props.IaudNAPNv ?? "300+",
		OshPD4ltJ: starRightTop ?? props.OshPD4ltJ,
		ppgC7wksI: starLeftTop ?? props.ppgC7wksI,
		t5s9sAXik: title ?? props.t5s9sAXik ?? "Design Concepts Explored",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "T4B4Qb96n",
		w1JxzH72Q: starRightBottom ?? props.w1JxzH72Q,
		y5UIh20pm: radius ?? props.y5UIh20pm ?? "16px",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		IaudNAPNv,
		t5s9sAXik,
		y5UIh20pm,
		ppgC7wksI,
		dlzgQhR5n,
		OshPD4ltJ,
		w1JxzH72Q,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "T4B4Qb96n",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-f7dliy",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop + Tablet"}
						layoutDependency={layoutDependency}
						layoutId={"T4B4Qb96n"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: radiusForCorner(y5UIh20pm, 3),
							borderBottomRightRadius: radiusForCorner(y5UIh20pm, 2),
							borderTopLeftRadius: radiusForCorner(y5UIh20pm, 0),
							borderTopRightRadius: radiusForCorner(y5UIh20pm, 1),
							...style,
						}}
						{...addPropertyOverrides(
							{
								jcZSVN2ZM: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1xobbfz"}
							data-border={true}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"p7sNc21kx"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5bb10796-193a-46db-ac69-0030f944c211, rgb(178, 201, 230))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: radiusForCorner(y5UIh20pm, 3),
								borderBottomRightRadius: radiusForCorner(y5UIh20pm, 2),
								borderTopLeftRadius: radiusForCorner(y5UIh20pm, 0),
								borderTopRightRadius: radiusForCorner(y5UIh20pm, 1),
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-z8os1d"}
								data-framer-name={"Number"}
								effect={textEffect}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"vobQg69uB"}
								style={{
									"--extracted-1of0zx5":
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={IaudNAPNv}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h2
										className={"framer-styles-preset-pyrh9q"}
										data-styles-preset={"RXS0p1P3P"}
										style={{
											"--framer-text-color":
												"var(--extracted-1of0zx5, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
										}}
									>
										{"300+"}
									</motion.h2>
								</React.Fragment>
							</RichText>
							<RichTextWithFX
								__framer__animate={{
									transition: transition3,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1mo4bxq"}
								data-framer-name={"Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"N_WuN1tib"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={t5s9sAXik}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-17e0ml2"}
										data-styles-preset={"Iwq8LBfrK"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-1615e446-4914-429c-9d6b-de0d358636dc, rgb(0, 74, 173)))",
										}}
									>
										{"Design Concepts Explored"}
									</motion.p>
								</React.Fragment>
							</RichTextWithFX>
							{ppgC7wksI && (
								<ComponentViewportProvider
									height={12}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 300) - 0 - 300) / 2 +
											0 +
											0) +
										-6
									}
									{...addPropertyOverrides(
										{
											jcZSVN2ZM: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 193) - 0 - 270) / 2 +
														0 +
														0) +
													-6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition4,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1hbt5c9-container"}
										data-framer-name={"Star - Left top"}
										layoutDependency={layoutDependency}
										layoutId={"fJUTh8ZRL-container"}
										name={"Star - Left top"}
										nodeId={"fJUTh8ZRL"}
										rendersWithMotion={true}
										scopeId={"vNoPOUtG5"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "fJUTh8ZRL",
											layoutId: "fJUTh8ZRL",
											name: "Star - Left top",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
							)}
							{OshPD4ltJ && (
								<ComponentViewportProvider
									height={12}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 300) - 0 - 300) / 2 +
											0 +
											0) +
										-6
									}
									{...addPropertyOverrides(
										{
											jcZSVN2ZM: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 193) - 0 - 270) / 2 +
														0 +
														0) +
													-6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition4,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-b4yrc8-container"}
										data-framer-name={"Star - Right top"}
										layoutDependency={layoutDependency}
										layoutId={"SQTm20ptw-container"}
										name={"Star - Right top"}
										nodeId={"SQTm20ptw"}
										rendersWithMotion={true}
										scopeId={"vNoPOUtG5"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "SQTm20ptw",
											layoutId: "SQTm20ptw",
											name: "Star - Right top",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
							)}
							{dlzgQhR5n && (
								<ComponentViewportProvider
									height={12}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 300) - 0 - 300) / 2 +
											0 +
											0) +
										300 -
										6
									}
									{...addPropertyOverrides(
										{
											jcZSVN2ZM: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 193) - 0 - 270) / 2 +
														0 +
														0) +
													270 -
													6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition4,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-14dc2wr-container"}
										data-framer-name={"Star - Left bottom"}
										layoutDependency={layoutDependency}
										layoutId={"LIGewLXCU-container"}
										name={"Star - Left bottom"}
										nodeId={"LIGewLXCU"}
										rendersWithMotion={true}
										scopeId={"vNoPOUtG5"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "LIGewLXCU",
											layoutId: "LIGewLXCU",
											name: "Star - Left bottom",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
							)}
							{w1JxzH72Q && (
								<ComponentViewportProvider
									height={12}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 300) - 0 - 300) / 2 +
											0 +
											0) +
										300 -
										6
									}
									{...addPropertyOverrides(
										{
											jcZSVN2ZM: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 193) - 0 - 270) / 2 +
														0 +
														0) +
													270 -
													6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition4,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-15tieaa-container"}
										data-framer-name={"Star - Right bottom"}
										layoutDependency={layoutDependency}
										layoutId={"j86eWnTHr-container"}
										name={"Star - Right bottom"}
										nodeId={"j86eWnTHr"}
										rendersWithMotion={true}
										scopeId={"vNoPOUtG5"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "j86eWnTHr",
											layoutId: "j86eWnTHr",
											name: "Star - Right bottom",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UGwME.framer-1tji49p, .framer-UGwME .framer-1tji49p { display: block; }",
	".framer-UGwME.framer-f7dliy { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 248px; }",
	".framer-UGwME .framer-1xobbfz { align-content: flex-start; align-items: flex-start; aspect-ratio: 0.8266666666666667 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: var(--framer-aspect-ratio-supported, 300px); justify-content: space-between; overflow: visible; padding: 32px; position: relative; width: 100%; }",
	".framer-UGwME .framer-z8os1d { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-UGwME .framer-1mo4bxq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-UGwME .framer-1hbt5c9-container { flex: none; height: auto; left: -6px; position: absolute; top: -6px; width: auto; z-index: 1; }",
	".framer-UGwME .framer-b4yrc8-container { flex: none; height: auto; position: absolute; right: -6px; top: -6px; width: auto; z-index: 1; }",
	".framer-UGwME .framer-14dc2wr-container { bottom: -6px; flex: none; height: auto; left: -6px; position: absolute; width: auto; z-index: 1; }",
	".framer-UGwME .framer-15tieaa-container { bottom: -6px; flex: none; height: auto; position: absolute; right: -6px; width: auto; z-index: 1; }",
	".framer-UGwME.framer-v-1mchtog .framer-1xobbfz { aspect-ratio: unset; gap: 50px; height: min-content; justify-content: center; padding: 16px; }",
	".framer-UGwME.framer-v-1mchtog .framer-1mo4bxq { max-width: 150px; }",
	...css2,
	...css,
	'.framer-UGwME[data-border="true"]::after, .framer-UGwME [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramervNoPOUtG5 = withCSS(Component, css3, "framer-UGwME");
var stdin_default2 = FramervNoPOUtG5;
FramervNoPOUtG5.displayName = "Statistics Card";
FramervNoPOUtG5.defaultProps = {
	height: 300,
	width: 248,
};
addPropertyControls(FramervNoPOUtG5, {
	variant: {
		options: ["T4B4Qb96n", "jcZSVN2ZM"],
		optionTitles: ["Desktop + Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	IaudNAPNv: {
		defaultValue: "300+",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	t5s9sAXik: {
		defaultValue: "Design Concepts Explored",
		displayTextArea: true,
		title: "Title",
		type: ControlType.String,
	},
	y5UIh20pm: {
		defaultValue: "16px",
		title: "Radius",
		type: ControlType.BorderRadius,
	},
	ppgC7wksI: {
		defaultValue: false,
		title: "Star Left top",
		type: ControlType.Boolean,
	},
	dlzgQhR5n: {
		defaultValue: false,
		title: "Star Left bottom",
		type: ControlType.Boolean,
	},
	OshPD4ltJ: {
		defaultValue: false,
		title: "Star Right top",
		type: ControlType.Boolean,
	},
	w1JxzH72Q: {
		defaultValue: false,
		title: "Star Right bottom",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramervNoPOUtG5,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...StarHeroFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:statistics-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "jcZSVN2ZM",
	xl: "T4B4Qb96n",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StatisticsCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var statistics_card_default = ComponentWithRoot;
export { statistics_card_default as default };
