// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UOQGEBQU.js";
import { className, css, fonts } from "./chunks/chunk-3XNB3BOA.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:testimonial-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/9JvZxzCeKhA5Hfm1qTBY/JFkET2Pww6PaGoQJHev0/X9gU9wVfW.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["Cbxfa3G5B", "lJpvDP9Do"];
var serializationHash = "framer-lKoVw";
var variantClassNames = {
	Cbxfa3G5B: "framer-v-hkq7tn",
	lJpvDP9Do: "framer-v-4lvpxo",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop + Tablet": "Cbxfa3G5B",
	Phone: "lJpvDP9Do",
};
var getProps = ({
	height,
	id,
	nameDesignation,
	reviewerImage,
	reviewText,
	width,
	...props
}) => {
	return {
		...props,
		H6TwcfHq8: reviewerImage ?? props.H6TwcfHq8,
		tpoBU_uzV:
			reviewText ??
			props.tpoBU_uzV ??
			"Working with James was an outstanding experience. His attention to detail, creative insight, and ability to translate ideas into stunning designs exceeded all our expectations.",
		uwTNtltLB:
			nameDesignation ??
			props.uwTNtltLB ??
			"Michael Thompson, Marketing Director",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Cbxfa3G5B",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		H6TwcfHq8,
		tpoBU_uzV,
		uwTNtltLB,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Cbxfa3G5B",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-hkq7tn",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop + Tablet"}
						layoutDependency={layoutDependency}
						layoutId={"Cbxfa3G5B"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								lJpvDP9Do: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-16r5ozl"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"OSQBX__b5"}
						>
							<motion.div
								className={"framer-1px6kto"}
								data-framer-name={"Image & Review Text"}
								layoutDependency={layoutDependency}
								layoutId={"ezc7Z385A"}
							>
								<motion.div
									className={"framer-1d9s7j5"}
									data-framer-name={"Reviewer Image"}
									layoutDependency={layoutDependency}
									layoutId={"PZNxOisGC"}
								>
									<Image
										as={"figure"}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 0 + 0 + 0,
											),
											sizes: "56px",
											...toResponsiveImage(H6TwcfHq8),
										}}
										className={"framer-33w2sb"}
										data-framer-name={"Reviewer Image"}
										layoutDependency={layoutDependency}
										layoutId={"p5yYRReJN"}
										style={{
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
										}}
									/>
									<Image
										as={"figure"}
										background={{
											alt: "Quote Icon",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 0 + 0 + 0,
											),
											pixelHeight: 56,
											pixelWidth: 56,
											src: "https://framerusercontent.com/images/1R3LFRyTCplS2OH8KjBd7kazsI.svg?width=56&height=56",
										}}
										className={"framer-14rwi7e"}
										data-framer-name={"Quote Icon"}
										layoutDependency={layoutDependency}
										layoutId={"jQeCBiW6_"}
									/>
								</motion.div>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-mli6td"}
									data-framer-name={"Review Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"IpHvfXzL9"}
									style={{
										"--extracted-1of0zx5":
											"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={tpoBU_uzV}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											className={"framer-styles-preset-pyrh9q"}
											data-styles-preset={"RXS0p1P3P"}
											style={{
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
											}}
										>
											{
												"Working with James was an outstanding experience. His attention to detail, creative insight, and ability to translate ideas into stunning designs exceeded all our expectations."
											}
										</motion.h2>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-yh3upj"}
								data-framer-name={"Name & Designation"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Cv1FW7xmG"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={uwTNtltLB}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-17e0ml2"}
										data-styles-preset={"Iwq8LBfrK"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-c2c7eb3e-53e2-457b-9354-efdcba611bee, rgb(246, 244, 240)))",
										}}
									>
										{"Michael Thompson, Marketing Director"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lKoVw.framer-1r58xbx, .framer-lKoVw .framer-1r58xbx { display: block; }",
	".framer-lKoVw.framer-hkq7tn { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 550px; }",
	".framer-lKoVw .framer-16r5ozl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-lKoVw .framer-1px6kto { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-lKoVw .framer-1d9s7j5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-lKoVw .framer-33w2sb { flex: none; height: 56px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 56px; will-change: var(--framer-will-change-override, transform); }",
	".framer-lKoVw .framer-14rwi7e { flex: none; height: 56px; overflow: visible; position: relative; width: 56px; }",
	".framer-lKoVw .framer-mli6td, .framer-lKoVw .framer-yh3upj { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-lKoVw.framer-v-4lvpxo.framer-hkq7tn { width: 350px; }",
	".framer-lKoVw.framer-v-4lvpxo .framer-16r5ozl { gap: 28px; }",
	".framer-lKoVw.framer-v-4lvpxo .framer-14rwi7e { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 36px); width: 36px; }",
	...css2,
	...css,
];
var FramerX9gU9wVfW = withCSS(Component, css3, "framer-lKoVw");
var stdin_default = FramerX9gU9wVfW;
FramerX9gU9wVfW.displayName = "Testimonial Card";
FramerX9gU9wVfW.defaultProps = {
	height: 446,
	width: 550,
};
addPropertyControls(FramerX9gU9wVfW, {
	variant: {
		options: ["Cbxfa3G5B", "lJpvDP9Do"],
		optionTitles: ["Desktop + Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	H6TwcfHq8: {
		title: "Reviewer Image",
		type: ControlType.ResponsiveImage,
	},
	tpoBU_uzV: {
		defaultValue:
			"Working with James was an outstanding experience. His attention to detail, creative insight, and ability to translate ideas into stunning designs exceeded all our expectations.",
		displayTextArea: true,
		title: "Review Text",
		type: ControlType.String,
	},
	uwTNtltLB: {
		defaultValue: "Michael Thompson, Marketing Director",
		displayTextArea: true,
		title: "Name & Designation",
		type: ControlType.String,
	},
});
addFonts(
	FramerX9gU9wVfW,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonial-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var testimonial_card_default = ComponentWithRoot;
export { testimonial_card_default as default };
