// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * text?: string // Text
 * font?: undefined // font
 * textColor?: string // textColor
 * startOffset?: number // Start Offset
 * endOffset?: number // End Offset
 * stiffness?: number // Stiffness
 * damping?: number // Damping
 * startOpacity?: number // Start Opacity
 * endOpacity?: number // End Opacity
}} Props

 */
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:text-reveal
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zTZT5VDWfdfpZmIlKBMo/rX5VylHR7xgIJdbkNCRw/Text_reveal.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import { motion, useScroll, useTransform, useSpring } from "unframer";
import { useRef, useEffect, useState } from "react";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var EachWord = ({
	word,
	starting,
	ending,
	startOpacity,
	endOpacity,
	progress,
	stiffness,
	damping,
}) => {
	const [sanitizedWord, setSanitizedWord] = useState(word);
	const progressVal = useTransform(
		progress,
		[starting, ending],
		[startOpacity, endOpacity],
	);
	const smoothProgress = useSpring(progressVal, {
		stiffness,
		damping,
	});
	const animationStyles = {
		opacity: smoothProgress,
		willChange: "opacity",
	};
	useEffect(() => {
		if (typeof __unframerWindow !== "undefined") {
			import("dompurify").then((DOMPurify) => {
				setSanitizedWord(DOMPurify.sanitize(word));
			});
		}
	}, [word]);
	return (
		<motion.span
			style={animationStyles}
			dangerouslySetInnerHTML={{
				__html: sanitizedWord,
			}}
		/>
	);
};
function Reveal(props) {
	const text = props.text;
	const words = text
		.split(/(<[^>]+>[^<]*<\/[^>]+>|<[^>]+>|[^<>\s]+)/g)
		.filter(Boolean);
	const totalWords = words.length;
	const ref = useRef(null);
	const { scrollYProgress } = useScroll({
		target: ref,
		offset: [`start ${props.startOffset}`, `end ${props.endOffset}`],
	});
	return (
		<p
			ref={ref}
			style={{
				...props.font,
				color: props.textColor,
				margin: 0,
				padding: 0,
			}}
		>
			{words.map((word, idx) => {
				const starting = idx / totalWords;
				const ending = (idx + 1) / totalWords;
				return (
					<EachWord
						word={word}
						starting={starting}
						ending={ending}
						startOpacity={props.startOpacity}
						endOpacity={props.endOpacity}
						progress={scrollYProgress}
						stiffness={props.stiffness}
						damping={props.damping}
					/>
				);
			})}
		</p>
	);
}
addPropertyControls(Reveal, {
	text: {
		title: "Text",
		type: ControlType.String,
		defaultValue:
			"Step into the future where each collection is a doorway to a different realm. <br><br>From the <b>nomadic trails</b> of the desert to the bustling streets of the urban jungle, our collections merge the <u>past's heritage</u> with the future's possibilities.<br><br>Futuristic architecture in the Amazon jungle",
		displayTextArea: true,
	},
	font: {
		type: "font",
		controls: "extended",
	},
	textColor: {
		type: ControlType.Color,
	},
	startOffset: {
		title: "Start Offset",
		type: ControlType.Number,
		defaultValue: 0.75,
		min: 0,
		max: 1,
		step: 0.01,
	},
	endOffset: {
		title: "End Offset",
		type: ControlType.Number,
		defaultValue: 0.15,
		min: 0,
		max: 1,
		step: 0.01,
	},
	stiffness: {
		title: "Stiffness",
		type: ControlType.Number,
		defaultValue: 100,
		min: 0,
		max: 1e3,
		step: 1,
	},
	damping: {
		title: "Damping",
		type: ControlType.Number,
		defaultValue: 20,
		min: 0,
		max: 100,
		step: 1,
	},
	startOpacity: {
		title: "Start Opacity",
		type: ControlType.Number,
		defaultValue: 0.1,
		min: 0,
		max: 1,
		step: 0.01,
	},
	endOpacity: {
		title: "End Opacity",
		type: ControlType.Number,
		defaultValue: 1,
		min: 0,
		max: 1,
		step: 0.01,
	},
});

// virtual:text-reveal
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<Reveal {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TextRevealFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={Reveal}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, Reveal);
var text_reveal_default = ComponentWithRoot;
export { text_reveal_default as default };
