// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 35026f80cf201b0d "An Nguyen Portfolio Final", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * backgroundFill?: boolean // Background Fill
 * background?: string // Background
 * padding?: number // Padding
 * gap?: number // Gap
 * showLocation?: boolean // Show Location
 * showTime?: boolean // Show Time
 * timeFormat?: '12 Hour' | '24 Hour' // Time Format
 * showSeconds?: boolean // Show Seconds
 * showDate?: boolean // Show Date
 * dateFormat?: 'Short' | 'Long' | 'Numeric' // Date Format
 * timeColor?: string // Time Color
 * locationColor?: string // Location Color
 * timeFont?: undefined // Time Font
 * locationFont?: undefined // Location Font
}} Props

 */
import { TimeDisplay } from "./chunks/chunk-LDJGA6JN.js";
import { routes } from "./chunks/chunk-YOGVINIF.js";

// virtual:time-display
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<TimeDisplay {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TimeDisplayFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"35026f80cf201b0def215202e5b380661d3189853be09c20baabfccb533e90ee"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={TimeDisplay}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, TimeDisplay);
var time_display_default = ComponentWithRoot;
export { time_display_default as default };
